export const ADMIN_COPY = Object.freeze({
  app: {
    title: 'Quản trị nội dung',
    subtitle: 'Trang xem và quản lý nội dung website triển lãm 3D',
    shortSubtitle: 'Triển lãm 3D',
    eyebrow: 'Quản trị nội dung',
    loginEyebrow: 'Đăng nhập quản trị',
    brandEyebrow: 'Không gian triển lãm',
    brandTitle: 'Trung tâm Văn hóa và Triển lãm',
    logoMark: 'ND',
    sidebarFooterTitle: 'Trang quản trị',
  },
  login: {
    fields: {
      email: 'Thư điện tử',
      password: 'Mật khẩu',
    },
    placeholders: {
      email: 'nguoiquantri@example.com',
      password: '••••••••',
    },
    submit: 'Đăng nhập',
    submitting: 'Đang đăng nhập...',
  },
  navGroups: [
    {
      key: 'overview',
      items: [{ key: 'dashboard', label: 'Tổng quan' }],
    },
    {
      key: 'website',
      label: 'Nội dung website',
      items: [
        { key: 'home', label: 'Trang chủ' },
        { key: 'gate', label: 'Cổng vào triển lãm' },
      ],
    },
    {
      key: 'gallery3d',
      label: 'Triển lãm 3D',
      items: [
        { key: 'staticDraft', label: 'Nội dung phòng 3D' },
        { key: 'media', label: 'Ảnh & video' },
      ],
    },
    {
      key: 'operations',
      label: 'Vận hành',
      items: [
        { key: 'publish', label: 'Đưa website lên bản mới' },
        { key: 'history', label: 'Lịch sử phiên bản' },
        { key: 'cleanup', label: 'Quét & dọn tệp' },
      ],
    },
    {
      key: 'settings',
      label: 'Cấu hình',
      items: [{ key: 'settings', label: 'Thông tin website' }],
    },
  ],
  nav: [
    { key: 'dashboard', label: 'Tổng quan' },
    { key: 'home', label: 'Trang chủ' },
    { key: 'gate', label: 'Cổng vào triển lãm' },
    { key: 'media', label: 'Ảnh & video' },
    { key: 'staticDraft', label: 'Nội dung phòng 3D' },
    { key: 'publish', label: 'Đưa website lên bản mới' },
    { key: 'history', label: 'Lịch sử phiên bản' },
    { key: 'cleanup', label: 'Quét & dọn tệp' },
    { key: 'settings', label: 'Thông tin website' },
  ],
  globalEdit: {
    cleanEditing: 'Đang chỉnh sửa — chưa có thay đổi.',
    noChanges: 'Chưa có thay đổi để lưu.',
    cancel: 'Hủy',
    reset: 'Đặt lại thay đổi',
    resetConfirm: 'Đặt lại các thay đổi chưa lưu trong form này?',
    resetSuccess: 'Đã đặt lại thay đổi chưa lưu.',
    leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
    savingBlocked: 'Đang lưu bản nháp, vui lòng chờ hoàn tất.',
    mobileSafeMode: 'Thiết bị này đang ở chế độ xem an toàn. Hãy dùng tablet hoặc máy tính để chỉnh sửa nội dung.',
    draftShort: 'Lưu tại CMS, chưa đổi website.',
    technicalLocked: 'Mã kỹ thuật và đường dẫn đang khóa để tránh lệch dữ liệu.',
    mediaReadonly: 'Ảnh/video chỉ xem. Thay media ở bước Media Upload sau.',
  },
  badges: {
    viewMode: 'Chế độ xem',
    lockedEditing: 'Chưa bật toàn CMS',
    editingEnabled: 'Đã bật chỉnh sửa',
  },
  help: {
    viewMode: {
      title: 'Chế độ xem là gì?',
      paragraphs: [
        'Bạn đang xem dữ liệu nội dung của website triển lãm.',
        'Ở chế độ này, mọi thao tác chỉ để xem thông tin, chưa làm thay đổi website.',
      ],
      listTitle: 'Bạn chưa thể:',
      bullets: [
        'Sửa phần lớn nội dung',
        'Tải ảnh hoặc video',
        'Đưa website lên bản mới',
        'Khôi phục phiên bản cũ',
      ],
      footer: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website đang chạy không bị ảnh hưởng.',
      button: 'Đã hiểu',
    },
    lockedEditing: {
      title: 'Vì sao chưa chỉnh sửa được?',
      paragraphs: [
        'Chức năng chỉnh sửa đang được khóa cho phần lớn nội dung để bảo vệ dữ liệu.',
        'Riêng màn Thông tin website, Cổng vào triển lãm và Khu vực đầu trang của Trang chủ có thể được bật chỉnh sửa bản nháp khi đủ quyền.',
      ],
      listTitle: 'Các chức năng sẽ được bật ở bước sau:',
      bullets: [
        'Chỉnh sửa thông tin website ở phạm vi hẹp',
        'Chỉnh sửa chữ hiển thị của Cổng vào triển lãm',
        'Chỉnh sửa Khu vực đầu trang của Trang chủ',
        'Chỉnh sửa tác phẩm',
        'Tải ảnh/video',
        'Kiểm tra và công khai nội dung',
      ],
      footer: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website không bị ảnh hưởng trong bước này.',
      button: 'Đã hiểu',
    },
  },
  pages: {
    dashboard: {
      title: 'Tổng quan',
      subtitle: 'Xem nhanh tình trạng website, việc cần làm tiếp theo và các khu vực có thể chỉnh sửa.',
    },
    home: {
      title: 'Trang chủ',
      subtitle: 'Kiểm tra nội dung hiển thị ở trang giới thiệu đầu tiên của website triển lãm.',
    },
    gate: {
      title: 'Cổng vào triển lãm',
      subtitle: 'Kiểm tra nội dung màn chọn không gian trước khi người xem vào tham quan.',
    },
    media: {
      title: 'Ảnh & video',
      subtitle: 'Xem, tìm, xem trước và lấy link ảnh/video đã có để dùng trong nội dung.',
    },
    staticDraft: {
      title: 'Nội dung phòng 3D',
      subtitle: 'Chỉnh nội dung, hình ảnh và video cho các phòng 3D. Website chỉ thay đổi sau khi công khai bản đã lưu.',
    },
    publish: {
      title: 'Đưa website lên bản mới',
      subtitle: 'Làm theo các bước: lưu bản nháp, kiểm tra an toàn, công khai bản đã lưu, rồi mở website để kiểm tra.',
    },
    history: {
      title: 'Lịch sử phiên bản',
      subtitle: 'Xem các phiên bản nội dung đã từng được công khai hoặc lưu trữ.',
    },
    cleanup: {
      title: 'Quét & dọn tệp',
      subtitle: 'Quét tệp, kiểm tra tệp có thể xóa, xem danh sách và chỉ xóa khi đã xác nhận.',
    },
    settings: {
      title: 'Thông tin website',
      subtitle: 'Xem và chỉnh sửa bản nháp thông tin website ở phạm vi an toàn.',
    },
  },
  staticDraft: {
    operatorSteps: {
      title: 'Các bước chỉnh triển lãm 3D',
      subtitle: 'Làm từ trên xuống: chọn nội dung, sửa, lưu, kiểm tra, rồi công khai khi sẵn sàng.',
      note: 'Lưu bản nháp chưa làm đổi website.',
      steps: [
        'Chọn phòng và tác phẩm.',
        'Sửa nội dung, ảnh hoặc video.',
        'Lưu bản nháp.',
        'Kiểm tra an toàn.',
        'Công khai bản đã lưu.',
      ],
    },
    mainTitle: 'Nội dung phòng 3D',
    statusReady: 'Đang sửa bản nháp',
    warning: 'Màn này chỉnh nội dung, ảnh và video cho các item đã có trong phòng 3D. Website chỉ thay đổi sau khi công khai nội dung.',
    load: 'Tải nội dung đang công khai',
    loading: 'Đang tải nội dung...',
    reset: 'Hoàn tác về lúc tải gần nhất',
    export: 'Xuất JSON kỹ thuật',
    copy: 'Sao chép JSON kỹ thuật',
    dirty: 'Có thay đổi chưa lưu',
    clean: 'Đã lưu / chưa có thay đổi',
    source: 'Nguồn nội dung',
    room: 'Phòng',
    item: 'Tác phẩm / item',
    fieldsTitle: 'Thông tin nội dung và media',
    previewTitle: 'Xem trước media',
    validationTitle: 'Kiểm tra trước khi công khai',
    exportTitle: 'Nâng cao',
    saveTitle: 'Quản lý bản nháp',
    saveDraft: 'Lưu bản nháp',
    saveAsNew: 'Lưu thành bản nháp mới',
    savedDrafts: 'Bản nháp đã lưu',
    notPublished: 'Nội dung chưa được công khai lên website.',
    noBaseline: 'Chưa tải nội dung hiện tại.',
    noItem: 'Chưa chọn tác phẩm / item.',
    sourceRemote: 'remote',
    sourceFallback: 'fallback',
    sourceLocal: 'local',
    sourceUnknown: 'chưa rõ',
  },
  dashboard: {
    websiteLink: 'Xem website',
    status: {
      title: 'Trạng thái website',
      currentVersion: 'Phiên bản nội dung website đang dùng',
      cmsRecordStatus: 'Trạng thái bản ghi CMS',
      dataSource: 'Dữ liệu CMS đang đọc',
      readOnlyMode: 'Chế độ hiện tại',
      publishedAt: 'Thời điểm bản ghi tham chiếu',
      website: 'Website đang hoạt động',
      safety: 'Chế độ xem an toàn',
      active: 'Đang hoạt động',
      safe: 'Chỉ xem, không thay đổi dữ liệu',
      readOnly: 'Chỉ xem',
      sourceNote: 'Nội dung website đang dùng được đọc từ bản nội dung public. Bản ghi tham chiếu chỉ để đối chiếu và có thể lệch nếu chưa đồng bộ.',
      canonicalSource: 'Nguồn chính: nội dung website đang dùng',
      fallbackSource: 'Nguồn dự phòng: dữ liệu tham chiếu',
      dbReferenceVersion: 'Phiên bản của bản ghi tham chiếu',
      dbReferenceNote: 'Bản ghi tham chiếu không phải nội dung website đang dùng trong quy trình công khai/khôi phục hiện tại.',
    },
    quickActions: {
      title: 'Đi nhanh',
      actions: [
        { key: 'home', label: 'Kiểm tra Trang chủ', note: 'Nội dung trang giới thiệu đầu tiên' },
        { key: 'gate', label: 'Kiểm tra Cổng vào triển lãm', note: 'Màn chọn không gian tham quan' },
        { key: 'staticDraft', label: 'Mở Nội dung phòng 3D', note: 'Chỉnh nội dung, ảnh và video cho các phòng 3D' },
      ],
      website: {
        label: 'Xem website',
        note: 'Mở trang đang chạy trong tab mới',
      },
    },
    metrics: {
      title: 'Số liệu nội dung',
      rooms: 'Không gian',
      artworks: 'Tác phẩm',
      indoor: 'Trong phòng',
      outdoor: 'Ngoài trời',
      media: 'Ảnh/video',
      featured: 'Tác phẩm tiêu biểu',
    },
    cards: {
      currentContent: {
        label: 'Nội dung website đang dùng',
        emptyNote: 'Chưa đọc được nội dung website đang dùng',
      },
      connection: {
        label: 'Kết nối dữ liệu',
        ok: 'Đang hoạt động',
        warning: 'Cần kiểm tra',
        okNote: 'Đọc dữ liệu thành công',
        warningNote: 'Một số nội dung chưa đọc được',
      },
    },
    tasks: {
      title: 'Việc cần chú ý',
      mediaEmpty: 'Thư viện ảnh/video hiện chưa có tệp nào.',
      warningAction: 'Mở Nội dung phòng 3D',
      locked: 'Chỉ một số màn được chỉnh sửa bản nháp. Upload, công khai và khôi phục vẫn đang khóa.',
      publicSafe: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website không bị ảnh hưởng trong bước này.',
      warningEmpty: 'Hiện chưa có cảnh báo nội dung cần xử lý.',
      canonicalWarningHint: 'Bấm để mở Nội dung phòng 3D. Các cảnh báo bên dưới được tính từ nội dung website đang dùng.',
      fallbackWarningHint: 'Bấm để mở Nội dung phòng 3D. Dashboard đang dùng DB catalog làm nguồn dự phòng. Các cảnh báo này chỉ là dữ liệu tham chiếu.',
      warningHint: 'Bấm để mở Nội dung phòng 3D. Các cảnh báo DB catalog chỉ là dữ liệu tham chiếu, website đổi qua bản nháp CMS.',
    },
    nextSteps: {
      title: 'Việc cần làm tiếp theo',
      subtitle: 'Làm theo các bước ngắn này để chỉnh nội dung mà không cần biết kỹ thuật.',
      note: 'Website chưa thay đổi cho đến khi bạn công khai bản đã lưu.',
      steps: [
        'Xem website đang dùng bản nào.',
        'Kiểm tra có cảnh báo nội dung không.',
        'Chọn màn cần chỉnh và lưu bản nháp.',
        'Chỉ công khai bản đã lưu khi đã kiểm tra an toàn.',
      ],
    },
    safety: {
      title: 'Trạng thái an toàn',
      body: 'Bạn đang xem nội dung ở chế độ chỉ xem. Chưa có thao tác nào làm thay đổi website đang chạy.',
    },
    panels: {
      siteSettings: 'Thông tin website',
      contentPublished: 'Bản ghi tham chiếu',
    },
  },
  contentViews: {
    home: {
      operatorSteps: {
        title: 'Các bước chỉnh Trang chủ',
        subtitle: 'Bạn có thể sửa phần chữ đã mở, lưu bản nháp rồi công khai sau.',
        note: 'Lưu bản nháp chưa làm đổi website.',
        steps: [
          'Chọn khu vực cần sửa.',
          'Sửa nội dung chữ/ảnh được phép.',
          'Lưu bản nháp.',
          'Công khai bản đã lưu khi muốn website thay đổi.',
        ],
      },
      sourceTitle: 'Dữ liệu Trang chủ đang đọc',
      emptyTitle: 'Chưa đọc được dữ liệu Trang chủ từ CMS',
      emptyBody: 'Kiểm tra bảng index_sections hoặc quyền xem dữ liệu. Không có nội dung giả được tạo trong màn này.',
      publicLink: 'Mở Trang chủ public',
      focusedEditNote: 'Đang chỉnh ở panel bên dưới.',
      sectionLabels: {
        hero: 'Khu vực đầu trang',
        experience: 'Khu vực trải nghiệm',
        guide: 'Hướng dẫn tham quan',
        contact: 'Thông tin liên hệ',
      },
      fields: {
        eyebrow: 'Nhãn nhỏ',
        title: 'Tiêu đề',
        subtitle: 'Tiêu đề phụ',
        lead: 'Mô tả ngắn',
        body: 'Nội dung mô tả',
        cta: 'Nút/CTA',
        media: 'Ảnh/video giới thiệu',
        items: 'Nội dung con',
        status: 'Trạng thái hiển thị',
        updatedAt: 'Cập nhật gần nhất',
      },
      presentation: {
        mainContent: 'Nội dung chính',
        cta: 'Nút/CTA',
        media: 'Ảnh/video giới thiệu',
        childItems: 'Danh sách nội dung con',
        statusInfo: 'Trạng thái nội dung',
        missingFields: 'Một số trường chưa khai báo',
        declaredData: 'Đã khai báo dữ liệu',
        dataFields: 'Trường dữ liệu',
        notDeclared: 'Chưa khai báo',
        buttonLabel: 'Nhãn nút',
        path: 'Đường dẫn',
        actionType: 'Loại hành động',
        caption: 'Chú thích',
        videoPath: 'Đường dẫn video',
        imagePath: 'Đường dẫn ảnh',
        fileType: 'Loại tệp',
        itemTitleFallback: 'Mục nội dung',
      },
      contactSource: {
        title: 'Nguồn dữ liệu liên hệ chính thức',
        notice: 'Thông tin liên hệ chính thức được quản lý tại Thông tin website.',
        detail: 'Địa chỉ, điện thoại, fax và email không chỉnh trong Trang chủ để tránh lệch nguồn dữ liệu.',
        publicNote: 'Chỉnh Thông tin website chỉ lưu vào CMS draft; website vẫn cần luồng công khai riêng.',
        mirrorTitle: 'Dữ liệu liên hệ đang dùng',
        sectionDataTitle: 'Nội dung section Contact hiện tại',
        openSettings: 'Mở Thông tin website',
        openSettingsTitle: 'Mở tab Thông tin website để chỉnh dữ liệu liên hệ chính thức',
        openSettingsAria: 'Mở Thông tin website để chỉnh dữ liệu liên hệ chính thức',
        settingsHint: 'Nếu cần cập nhật thông tin liên hệ chính thức, hãy chỉnh tại Thông tin website; không tạo bản sao trong Trang chủ.',
        readonly: 'Contact section đang ở chế độ chỉ xem.',
        missing: 'Chưa khai báo',
        fields: {
          organization: 'Đơn vị quản lý',
          address: 'Địa chỉ',
          phone: 'Điện thoại',
          fax: 'Fax',
          email: 'Email',
        },
      },
      safety: 'Màn này chỉ chỉnh sửa bản nháp cho Khu vực đầu trang. Các phần Trang chủ khác vẫn đang chỉ xem.',
      edit: {
        title: 'Chỉnh sửa Khu vực đầu trang',
        enabledScope: 'Chỉ bật chỉnh sửa Khu vực đầu trang',
        readOnlyScope: 'Các phần Trang chủ khác vẫn đang chỉ xem.',
        button: 'Chỉnh sửa phần này',
        cancel: 'Hủy',
        reset: 'Đặt lại thay đổi',
        save: 'Lưu bản nháp',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị. Đường dẫn media, CTA link, thứ tự và trạng thái hiển thị được khóa ở bước này.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Trang chủ hoặc chưa bật chỉnh sửa Khu vực đầu trang.',
        mediaReadonlyNote: 'Đường dẫn media chỉ xem ở bước này. Chức năng thay media sẽ mở sau khi có Media Upload.',
        ctaReadonlyNote: 'Đường dẫn CTA chỉ xem ở bước này. Không tự tạo route/link mới.',
        itemsReadonlyNote: 'Không thể thêm, xóa hoặc sắp xếp lại mục con ở bước này.',
        technicalReadonlyNote: 'Thông tin kỹ thuật chỉ xem, không chỉnh trong bước này.',
        noCtaLabel: 'Chưa có nhãn CTA có thể chỉnh sửa trong dữ liệu gốc.',
        unsupportedItems: 'Cấu trúc nội dung con chưa hỗ trợ chỉnh sửa ở bước này.',
        emptyItems: 'Danh sách nội dung con đang trống.',
        groups: {
          main: 'Nội dung chính',
          media: 'Ảnh/video giới thiệu',
          items: 'Danh sách nội dung con',
          cta: 'Nút/CTA',
          technical: 'Thông tin kỹ thuật chỉ xem',
        },
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề',
          subtitle: 'Tiêu đề phụ',
          lead: 'Mô tả ngắn',
          body: 'Nội dung mô tả',
          mediaCaption: 'Chú thích media',
          mediaPath: 'Đường dẫn media',
          mediaType: 'Loại media',
          item: 'Mục',
          itemText: 'Nội dung mục',
          itemDescription: 'Mô tả mục',
          ctaLabel: 'Nhãn nút',
          ctaPath: 'Đường dẫn CTA',
          sectionKey: 'Mã section',
          sortOrder: 'Thứ tự hiển thị',
          visible: 'Trạng thái hiển thị',
          updatedAt: 'Cập nhật gần nhất',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề khu vực đầu trang',
          subtitle: 'Nhập tiêu đề phụ',
          lead: 'Nhập mô tả ngắn',
          body: 'Nhập nội dung mô tả',
          mediaCaption: 'Nhập chú thích ảnh/video',
          itemText: 'Nhập nội dung mục',
          itemDescription: 'Nhập mô tả mục',
          ctaLabel: 'Nhập nhãn nút',
        },
        errors: {
          titleRequired: 'Tiêu đề Khu vực đầu trang không được để trống.',
          sectionInvalid: 'Chỉ chỉnh sửa Khu vực đầu trang ở bước này.',
          mediaInvalid: 'Dữ liệu ảnh/video giới thiệu không hợp lệ.',
          itemsInvalid: 'Dữ liệu nội dung con không hợp lệ.',
          itemsCountChanged: 'Không thể thêm, xóa hoặc sắp xếp lại mục con ở bước này.',
        },
        warnings: {
          titleLong: 'Tiêu đề khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          leadLong: 'Mô tả ngắn khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          bodyLong: 'Nội dung mô tả khá dài. Nên kiểm tra lại trước khi công khai.',
          mediaCaptionEmpty: 'Chú thích media đang trống. Nên kiểm tra lại trước khi công khai.',
          mediaCaptionLong: 'Chú thích media khá dài. Nên rút gọn trước khi công khai.',
          itemTitleLong: 'Nội dung mục khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionLong: 'Mô tả mục khá dài. Nên kiểm tra lại cách hiển thị.',
          ctaLabelLong: 'Nhãn nút khá dài. Nên rút gọn trước khi công khai.',
        },
      },
      guideEdit: {
        title: 'Chỉnh sửa Hướng dẫn tham quan',
        enabledScope: 'Chỉ bật chỉnh sửa Hướng dẫn tham quan',
        readOnlyScope: 'Khu vực trải nghiệm và Thông tin liên hệ vẫn giữ phạm vi riêng; Hướng dẫn chỉ sửa chữ ở panel này.',
        button: 'Chỉnh sửa phần này',
        buttonTitle: 'Chỉnh sửa chữ hiển thị của Hướng dẫn tham quan',
        buttonAria: 'Chỉnh sửa chữ hiển thị của Hướng dẫn tham quan',
        cancel: 'Hủy',
        cancelTitle: 'Hủy chỉnh sửa Hướng dẫn tham quan',
        cancelAria: 'Hủy chỉnh sửa Hướng dẫn tham quan',
        reset: 'Đặt lại thay đổi',
        resetTitle: 'Đặt lại thay đổi chưa lưu của Hướng dẫn tham quan',
        resetAria: 'Đặt lại thay đổi chưa lưu của Hướng dẫn tham quan',
        save: 'Lưu bản nháp',
        saveTitle: 'Lưu Hướng dẫn tham quan vào bản nháp CMS',
        saveAria: 'Lưu Hướng dẫn tham quan vào bản nháp CMS',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website.',
        publicNote: 'Website chỉ thay đổi sau khi bản nháp được lưu và công khai trong luồng riêng.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị của Hướng dẫn tham quan. CTA, media, thứ tự bước và dữ liệu kỹ thuật được khóa ở bước này.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Trang chủ hoặc chưa bật chỉnh sửa Hướng dẫn tham quan.',
        itemsReadonlyNote: 'Không thể thêm, xóa hoặc sắp xếp lại bước hướng dẫn ở bước này.',
        itemContractNote: 'Chỉ cập nhật tên và mô tả đang có; số lượng, thứ tự, route/link và metadata vẫn chỉ xem.',
        technicalAria: 'Thông tin kỹ thuật chỉ xem của Hướng dẫn tham quan',
        technicalReadonlyNote: 'Thông tin kỹ thuật chỉ xem, không chỉnh trong bước này.',
        unsupportedItems: 'Cấu trúc bước hướng dẫn chưa hỗ trợ chỉnh sửa ở bước này.',
        emptyItems: 'Danh sách bước hướng dẫn đang trống.',
        groups: {
          main: 'Nội dung chính',
          items: 'Danh sách bước hướng dẫn',
          technical: 'Thông tin kỹ thuật chỉ xem',
        },
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề',
          subtitle: 'Tiêu đề phụ',
          lead: 'Mô tả ngắn',
          body: 'Nội dung mô tả',
          step: 'Bước',
          stepText: 'Tên bước',
          stepTitle: 'Tên bước',
          stepDescription: 'Mô tả bước',
          readonlyMeta: 'Thông tin chỉ xem',
          sectionKey: 'Mã section',
          sortOrder: 'Thứ tự hiển thị',
          visible: 'Trạng thái hiển thị',
          itemCount: 'Số lượng bước',
          updatedAt: 'Cập nhật gần nhất',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề Hướng dẫn tham quan',
          subtitle: 'Nhập tiêu đề phụ',
          lead: 'Nhập mô tả ngắn',
          body: 'Nhập nội dung mô tả',
          stepText: 'Nhập tên bước',
          stepTitle: 'Nhập tên bước',
          stepDescription: 'Nhập mô tả bước',
        },
        errors: {
          titleRequired: 'Tiêu đề Hướng dẫn tham quan không được để trống.',
          sectionInvalid: 'Chỉ chỉnh sửa Hướng dẫn tham quan ở bước này.',
          itemsInvalid: 'Dữ liệu bước hướng dẫn không hợp lệ hoặc chưa hỗ trợ chỉnh sửa chữ ở bước này.',
          itemsCountChanged: 'Số lượng hoặc thứ tự bước đã thay đổi. Phase này chỉ cho sửa chữ của các bước hiện có.',
        },
        warnings: {
          titleLong: 'Tiêu đề khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          leadLong: 'Mô tả ngắn khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          bodyLong: 'Nội dung mô tả khá dài. Nên kiểm tra lại trước khi công khai.',
          itemTitleLong: 'Tên bước khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionLong: 'Mô tả bước khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionEmpty: 'Mô tả bước đang trống, nên kiểm tra trước khi công khai.',
          itemsShort: 'Hướng dẫn có ít hơn 2 bước. Nên kiểm tra lại trước khi công khai.',
          itemsEmpty: 'Danh sách bước hướng dẫn đang trống.',
        },
      },

      experienceEdit: {
        title: 'Chỉnh sửa Khu vực trải nghiệm',
        enabledScope: 'Chỉ bật chỉnh sửa Khu vực trải nghiệm',
        readOnlyScope: 'Thông tin liên hệ vẫn đang chỉ xem; Contact chính thức quản lý tại Thông tin website.',
        button: 'Chỉnh sửa phần này',
        buttonTitle: 'Chỉnh sửa chữ hiển thị của Khu vực trải nghiệm',
        buttonAria: 'Chỉnh sửa chữ hiển thị của Khu vực trải nghiệm',
        cancel: 'Hủy',
        cancelTitle: 'Hủy chỉnh sửa Khu vực trải nghiệm',
        cancelAria: 'Hủy chỉnh sửa Khu vực trải nghiệm',
        reset: 'Đặt lại thay đổi',
        resetTitle: 'Đặt lại thay đổi chưa lưu của Khu vực trải nghiệm',
        resetAria: 'Đặt lại thay đổi chưa lưu của Khu vực trải nghiệm',
        save: 'Lưu bản nháp',
        saveTitle: 'Lưu Khu vực trải nghiệm vào bản nháp CMS',
        saveAria: 'Lưu Khu vực trải nghiệm vào bản nháp CMS',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website.',
        publicNote: 'Website chỉ thay đổi sau khi bản nháp được lưu và công khai trong luồng riêng.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị của Khu vực trải nghiệm. Mã phòng, đường dẫn tham quan, CTA và media được khóa ở bước này.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Trang chủ hoặc chưa bật chỉnh sửa Khu vực trải nghiệm.',
        itemsReadonlyNote: 'Không thể thêm, xóa hoặc sắp xếp lại card trải nghiệm ở bước này.',
        routeReadonlyNote: 'Mã phòng, nhãn nút vào phòng và đường dẫn tham quan chỉ xem ở bước này.',
        protectedContractNote: 'Chỉ cập nhật chữ hiển thị của card hiện có; room key, route/path/link, CTA và thứ tự card vẫn được bảo vệ.',
        technicalAria: 'Thông tin kỹ thuật chỉ xem của Khu vực trải nghiệm',
        technicalReadonlyNote: 'Thông tin kỹ thuật chỉ xem, không chỉnh trong bước này.',
        unsupportedItems: 'Cấu trúc card trải nghiệm chưa hỗ trợ chỉnh sửa ở bước này.',
        emptyItems: 'Danh sách card trải nghiệm đang trống.',
        groups: {
          main: 'Nội dung chính',
          items: 'Danh sách card trải nghiệm',
          technical: 'Thông tin kỹ thuật chỉ xem',
        },
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề',
          subtitle: 'Tiêu đề phụ',
          lead: 'Mô tả ngắn',
          body: 'Nội dung mô tả',
          card: 'Card',
          cardText: 'Tên card',
          cardTitle: 'Tên card',
          cardDescription: 'Mô tả card',
          roomKey: 'Mã phòng',
          ctaLabel: 'Nhãn nút vào phòng',
          route: 'Đường dẫn tham quan',
          readonlyMeta: 'Thông tin chỉ xem',
          sectionKey: 'Mã section',
          sortOrder: 'Thứ tự hiển thị',
          visible: 'Trạng thái hiển thị',
          itemCount: 'Số lượng card',
          updatedAt: 'Cập nhật gần nhất',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề Khu vực trải nghiệm',
          subtitle: 'Nhập tiêu đề phụ',
          lead: 'Nhập mô tả ngắn',
          body: 'Nhập nội dung mô tả',
          cardText: 'Nhập tên card',
          cardTitle: 'Nhập tên card',
          cardDescription: 'Nhập mô tả card',
        },
        errors: {
          titleRequired: 'Tiêu đề Khu vực trải nghiệm không được để trống.',
          sectionInvalid: 'Chỉ chỉnh sửa Khu vực trải nghiệm ở bước này.',
          itemsInvalid: 'Dữ liệu card trải nghiệm không hợp lệ hoặc chưa hỗ trợ chỉnh sửa chữ ở bước này.',
          itemsCountChanged: 'Số lượng hoặc thứ tự card đã thay đổi. Phase này chỉ cho sửa chữ của các card hiện có.',
          protectedFieldChanged: 'Metadata kỹ thuật của card đã thay đổi. Room key, route/path/link và CTA chỉ xem ở bước này.',
        },
        warnings: {
          titleLong: 'Tiêu đề khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          leadLong: 'Mô tả ngắn khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          bodyLong: 'Nội dung mô tả khá dài. Nên kiểm tra lại trước khi công khai.',
          itemTitleLong: 'Tên card khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionLong: 'Mô tả card khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionEmpty: 'Mô tả card đang trống, nên kiểm tra trước khi công khai.',
          itemsShort: 'Khu vực trải nghiệm có ít hơn 2 card. Nên kiểm tra lại trước khi công khai.',
        },
      },
    },
    gate: {
      operatorSteps: {
        title: 'Các bước chỉnh Cổng vào triển lãm',
        subtitle: 'Chỉ sửa chữ hiển thị và nút vào phòng; đường dẫn kỹ thuật vẫn được khóa.',
        note: 'Lưu bản nháp chưa làm đổi website.',
        steps: [
          'Sửa tiêu đề, mô tả và nút vào phòng.',
          'Kiểm tra nội dung hai không gian.',
          'Lưu bản nháp.',
          'Công khai bản đã lưu nếu muốn website thay đổi.',
        ],
      },
      sourceTitle: 'Dữ liệu Cổng vào triển lãm đang đọc',
      emptyTitle: 'Chưa đọc được dữ liệu Cổng vào triển lãm từ CMS',
      emptyBody: 'Kiểm tra bảng gate_content hoặc quyền xem dữ liệu. Không có nội dung giả được tạo trong màn này.',
      publicLink: 'Mở Cổng vào triển lãm',
      mainInfo: 'Thông tin chính',
      roomsInfo: 'Lựa chọn không gian',
      fields: {
        eyebrow: 'Nhãn nhỏ',
        title: 'Tiêu đề cổng vào',
        description: 'Mô tả hướng dẫn',
        backLabel: 'Nhãn quay lại Trang chủ',
        active: 'Trạng thái sử dụng',
        updatedAt: 'Cập nhật gần nhất',
        roomTitle: 'Tên hiển thị',
        roomDescription: 'Mô tả không gian',
        roomCta: 'Nút bắt đầu tham quan',
        roomKey: 'Mã phòng kỹ thuật',
      },
      safety: 'Màn này chỉ xem nội dung hiển thị. Mã phòng, query vào phòng và luồng kỹ thuật không thay đổi ở đây.',
      edit: {
        title: 'Chỉnh sửa Cổng vào triển lãm',
        enabledScope: 'Chỉ bật chỉnh sửa Cổng vào triển lãm',
        readOnlyScope: 'Trang chủ và các khu vực khác vẫn đang chỉ xem.',
        button: 'Chỉnh sửa Cổng vào',
        cancel: 'Hủy',
        reset: 'Đặt lại thay đổi',
        save: 'Lưu bản nháp',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Cổng vào triển lãm.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị. Mã phòng, query vào phòng, route và dữ liệu kỹ thuật được khóa ở bước này.',
        technicalTitle: 'Thông tin kỹ thuật chỉ xem',
        editorReadonly: 'editor_json không chỉnh ở bước này để tránh ảnh hưởng luồng kỹ thuật.',
        noCtaLabel: 'Chưa khai báo nhãn nút bắt đầu tham quan trong dữ liệu gốc.',
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề cổng vào',
          description: 'Mô tả hướng dẫn',
          back_label: 'Nhãn quay lại Trang chủ',
          displayName: 'Tên hiển thị',
          roomDescription: 'Mô tả không gian',
          ctaLabel: 'Nhãn nút bắt đầu tham quan',
          roomKey: 'Mã phòng kỹ thuật',
          route: 'Đường dẫn tham quan',
          active: 'Trạng thái sử dụng',
        },
        groups: {
          main: 'Thông tin chính',
          indoor: 'Không gian trong nhà',
          outdoor: 'Không gian ngoài trời',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề cổng vào',
          description: 'Nhập mô tả hướng dẫn',
          back_label: 'Ví dụ: Quay lại Trang chủ',
          displayName: 'Nhập tên hiển thị',
          roomDescription: 'Nhập mô tả không gian',
          ctaLabel: 'Ví dụ: Bắt đầu tham quan',
        },
        errors: {
          titleRequired: 'Tiêu đề cổng vào không được để trống.',
          roomsInvalid: 'Dữ liệu lựa chọn không gian không hợp lệ.',
          indoorMissing: 'Thiếu dữ liệu không gian trong nhà.',
          outdoorMissing: 'Thiếu dữ liệu không gian ngoài trời.',
          indoorInvalid: 'Dữ liệu không gian trong nhà không hợp lệ.',
          outdoorInvalid: 'Dữ liệu không gian ngoài trời không hợp lệ.',
          indoorNameRequired: 'Không gian trong nhà cần có tên hiển thị.',
          outdoorNameRequired: 'Không gian ngoài trời cần có tên hiển thị.',
        },
        warnings: {
          descriptionEmpty: 'Mô tả đang trống, nên kiểm tra trước khi công khai.',
          indoorDescriptionEmpty: 'Mô tả không gian trong nhà đang trống, nên kiểm tra trước khi công khai.',
          outdoorDescriptionEmpty: 'Mô tả không gian ngoài trời đang trống, nên kiểm tra trước khi công khai.',
          titleLong: 'Tiêu đề cổng vào khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          descriptionLong: 'Mô tả hướng dẫn khá dài. Nên kiểm tra lại trước khi công khai.',
          roomTitleLong: 'Tên hiển thị khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          roomDescriptionLong: 'Mô tả không gian khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          ctaLong: 'Nhãn nút bắt đầu tham quan khá dài. Nên rút gọn trước khi công khai.',
        },
      },
    },
  },
  planningScreens: {
    home: {
      title: 'Trang chủ',
      status: 'Chỉ xem định hướng',
      intro: 'Đây là nơi sẽ quản lý nội dung hiển thị ở trang giới thiệu đầu tiên của website triển lãm.',
      sectionsTitle: 'Các phần sẽ quản lý',
      sections: [
        'Khu vực đầu trang',
        'Tiêu đề và mô tả giới thiệu',
        'Ảnh/video giới thiệu',
        'Nút vào triển lãm',
        'Khu vực trải nghiệm',
        'Hướng dẫn tham quan',
      ],
      noteTitle: 'Trạng thái hiện tại',
      note: 'Chức năng chỉnh sửa Trang chủ sẽ được bật ở bước sau. Hiện tại bạn chỉ xem định hướng nội dung.',
    },
    gate: {
      title: 'Cổng vào triển lãm',
      status: 'Không thay đổi luồng kỹ thuật',
      intro: 'Đây là nơi sẽ kiểm tra nội dung màn chọn không gian trước khi người xem vào tham quan.',
      sectionsTitle: 'Các phần sẽ quản lý',
      sections: [
        'Tiêu đề cổng vào',
        'Mô tả hướng dẫn chọn không gian',
        'Lựa chọn Không gian trong nhà',
        'Lựa chọn Không gian ngoài trời',
        'Nút bắt đầu tham quan',
        'Link quay lại trang chủ',
      ],
      noteTitle: 'Giới hạn an toàn',
      note: 'Màn này chỉ quản lý chữ và mô tả hiển thị. Mã phòng, đường dẫn vào phòng và luồng kỹ thuật không thay đổi ở đây.',
    },
  },
  media: {
    operatorSteps: {
      title: 'Cách dùng ảnh & video',
      subtitle: 'Màn này giúp xem lại media đã có và lấy link để gắn vào nội dung.',
      note: 'Xem, lọc, xem trước hoặc sao chép link không làm thay đổi website.',
      steps: [
        'Xem media đã có.',
        'Xem trước ảnh hoặc video.',
        'Sao chép link nếu cần.',
        'Gắn media trong màn chỉnh nội dung tương ứng.',
      ],
    },
    mainTitle: 'Thư viện ảnh & video',
    countLabel: 'tệp',
    emptyTitle: 'Chưa có media đã upload',
    intro: 'Chưa đọc được media nào từ nhật ký upload CMS.',
    body: 'Ảnh/video sẽ xuất hiện sau khi upload qua các flow hiện có. Màn này chỉ dùng để xem lại, lọc, preview, sao chép đường dẫn hoặc chọn media cho bản nháp.',
    emptyBadge: 'Chỉ xem',
    readOnlyBadge: 'Chỉ xem',
    uploadTypesTitle: 'Ảnh/video sẽ xuất hiện ở đây sau khi upload từ',
    uploadTypes: ['Nội dung phòng 3D', 'Ảnh Featured trang chủ', 'Poster video', 'Video thuyết minh'],
    safeNotice: 'Màn này chỉ xem, tìm, lọc, preview, sao chép đường dẫn và chọn media cho bản nháp. Không upload, không xóa, không công khai nội dung.',
    readOnlyNotice: 'Website không thay đổi khi bạn xem, lọc, preview, copy đường dẫn hoặc đi tới nơi dùng media.',
    metadataSource: 'Đọc từ nhật ký upload CMS',
    searchPlaceholder: 'Tìm theo tên file, đường dẫn, phòng, item hoặc URL',
    searchAriaLabel: 'Tìm media theo tên file, đường dẫn, phòng, item hoặc URL',
    filters: {
      allKinds: 'Tất cả loại media',
      allUsage: 'Tất cả trạng thái sử dụng',
      allTargets: 'Tất cả nơi dùng',
    },
    filterAriaLabels: {
      kind: 'Lọc theo loại media',
      usage: 'Lọc theo trạng thái sử dụng',
      target: 'Lọc theo nơi dùng',
    },
    kindLabels: {
      image: 'Ảnh',
      poster: 'Poster',
      video: 'Video',
      unknown: 'Ảnh/video',
    },
    targetLabels: {
      room_artwork: 'Nội dung phòng 3D',
      index_featured: 'Featured trang chủ',
      unknown: 'Chưa rõ nơi dùng',
    },
    usageLabels: {
      public: 'Đang dùng trên website',
      draft: 'Đang dùng trong bản nháp',
      cms: 'Đang dùng trong CMS',
      none: 'Chưa thấy tham chiếu',
      insufficient: 'Không đủ dữ liệu để kết luận',
    },
    usageNotes: {
      none: 'Chưa thấy tham chiếu trong dữ liệu đã kiểm tra. Không đồng nghĩa media an toàn để xóa.',
      insufficient: 'Không đủ dữ liệu để kết luận media đang dùng hay không.',
    },
    referencesTitle: 'Tham chiếu tìm thấy',
    referencesIntro: 'Dữ liệu tham chiếu chỉ để operator biết media đang xuất hiện ở đâu trong CMS đã kiểm tra.',
    referenceMore: 'tham chiếu khác',
    referenceFields: {
      source: 'Nguồn',
      area: 'Khu vực',
      field: 'Field/path',
      target: 'Màn điều hướng',
      confidence: 'Độ khớp',
    },
    referenceSourceLabels: {
      public: 'Website',
      draft: 'Bản nháp CMS',
      cms: 'CMS',
      unknown: 'Không rõ nguồn',
    },
    referenceMatchLabels: {
      strong: 'Khớp URL/path chính xác',
      weak: 'Khớp yếu',
      unknown: 'Không rõ',
    },
    fields: {
      uploadTime: 'Ngày upload',
      fileSize: 'Dung lượng',
      target: 'Nơi dùng',
      room: 'Phòng',
      item: 'Item',
      field: 'Trường media',
      status: 'Trạng thái kỹ thuật từ nhật ký upload',
      url: 'Đường dẫn',
    },
    statusNote: 'Trạng thái này chỉ là metadata upload, không dùng để kết luận media đang được dùng hay vòng đời media.',
    actions: {
      copyUrl: 'Sao chép đường dẫn',
      copyUrlAria: 'Sao chép đường dẫn media',
      copied: 'Đã sao chép',
      copyFailed: 'Không sao chép được',
      goToReference: 'Đi tới nơi dùng',
    },
    referenceNavigationHint: 'Chỉ điều hướng trong CMS, không thay đổi website.',
    operatorHandoffNotes: [
      'Copy đường dẫn không làm thay đổi website.',
      'Website chỉ thay đổi sau khi bạn lưu và công khai nội dung bằng flow riêng.',
      'Chưa thấy tham chiếu không đồng nghĩa media an toàn để xóa.',
      'Dọn dẹp tệp là quy trình riêng, không nằm trong màn Media Library.',
    ],
    emptyFiltered: 'Không có media nào khớp bộ lọc hiện tại. Hãy đổi từ khóa hoặc bộ lọc; trạng thái này không phải kết luận vòng đời media.',
    previewUnavailable: 'Không có preview an toàn cho media này.',
    previewError: 'Không tải được preview.',
    unsafeUrl: 'Đường dẫn media không thuộc nguồn được phép.',
    deleteDisabled: 'Không có thao tác dọn tệp ở màn này. Ảnh/video đang dùng, chưa thấy tham chiếu hoặc thiếu dữ liệu đều phải đi qua quy trình dọn dẹp riêng.',
    technicalTitle: 'Thông tin kỹ thuật, chỉ để đối chiếu',
    technicalRows: [
      ['Nơi lưu ảnh/video', 'Đã cấu hình', 'cms-media'],
      ['Nguồn danh sách thư viện', 'Đã cấu hình', 'cms_media_uploads'],
      ['Nơi lưu nội dung website', 'Đã cấu hình', 'cms-public'],
    ],
  },
  publish: {
    operatorSteps: {
      title: 'Các bước đưa website lên bản mới',
      subtitle: 'Màn này chỉ hướng dẫn và kiểm tra trạng thái. Công khai thật vẫn cần đi qua bản nháp đã lưu.',
      note: 'Website chỉ thay đổi ở bước công khai thật và vẫn cần xác nhận rõ.',
      steps: [
        'Lưu bản nháp.',
        'Kiểm tra an toàn.',
        'Công khai bản đã lưu.',
        'Mở website để kiểm tra.',
      ],
    },
    currentTitle: 'Bản ghi tham chiếu',
    noCurrent: 'Chưa đọc được bản ghi tham chiếu.',
    currentHint: 'Bản ghi tham chiếu chỉ để đối chiếu. Nội dung website đang dùng được lấy từ bản public; lịch sử vận hành ghi lại các lần công khai/khôi phục. Màn này không tự công khai và không ghi dữ liệu khi mở.',
    canonicalHint: 'Khi cần xác định website đang dùng nội dung nào, ưu tiên bản nội dung website đang dùng và lịch sử vận hành. Bản ghi tham chiếu chỉ để đối chiếu.',
    dbReferenceHint: 'Bản ghi tham chiếu có thể lệch với nội dung website đang dùng. Không dùng bản ghi này để quyết định website hiện tại nếu có dữ liệu public mới hơn.',
    surfaceTitle: 'Bề mặt trạng thái công khai',
    surfaceStatus: 'Chỉ xem trạng thái',
    surfaceBody: 'Màn Đưa website lên bản mới chỉ tổng hợp trạng thái và điều kiện trước khi công khai. Thao tác công khai thật vẫn nằm trong Nội dung phòng 3D / cổng công khai bản nháp đã lưu.',
    workflowTitle: 'Các bước đưa website lên bản mới',
    workflowStatus: 'Màn chính đang khóa thao tác ghi',
    workflowSteps: [
      'Lưu bản nháp bằng nút lưu rõ ràng.',
      'Kiểm tra an toàn cho bản nháp đã lưu.',
      'Chỉ công khai bản đã lưu sau khi kiểm tra an toàn đạt và người vận hành xác nhận.',
      'Kiểm tra Lịch sử phiên bản nếu cần khôi phục.',
    ],
    actions: ['Xem trạng thái', 'Kiểm tra điều kiện', 'Công khai từ bản nháp đã lưu'],
    disabledActionReason: 'Màn chính chỉ hiển thị trạng thái sẵn sàng. Không có thao tác công khai trực tiếp ở đây.',
    notice: 'Website chỉ thay đổi sau khi bấm công khai thật và xác nhận. Lưu bản nháp, sao chép, xem trước hoặc mở màn này không làm thay đổi website.',
    lockedNote: 'Màn này hướng dẫn các bước công khai. Hãy mở Nội dung phòng 3D, lưu bản nháp, kiểm tra an toàn rồi công khai bản đã lưu khi sẵn sàng.',
    publicLink: 'Kiểm tra website',
    readinessTitle: 'Kiểm tra trước khi công khai',
    readinessStatus: 'Không ghi dữ liệu',
    readinessIntro: 'Các mục dưới đây chỉ đọc trạng thái đã tải sẵn. Ưu tiên nội dung website đang dùng và lịch sử vận hành; bản ghi tham chiếu chỉ để đối chiếu.',
    disabledReasonsTitle: 'Vì sao tab này không có nút công khai trực tiếp',
    disabledReasons: [
      'Cần dùng bản nháp CMS đã lưu trên server, không dùng JSON thô từ trình duyệt.',
      'Kiểm tra an toàn phải đạt trước khi công khai thật.',
      'Công khai thật cần quyền quản trị đang hoạt động và xác nhận rõ ràng.',
      'Công khai thật đi qua bộ kiểm tra trên server; chỉ thao tác khi đã hiểu website sẽ thay đổi.',
      'Lịch sử phiên bản và khôi phục là quy trình riêng, không tự chạy từ màn trạng thái này.',
    ],
    requirementsTitle: 'Điều kiện trước khi công khai thật',
    requirements: [
      'Có bản nháp CMS đã lưu và không còn thay đổi chưa lưu.',
      'Kiểm tra nội dung đạt trước khi kiểm tra an toàn.',
      'Kiểm tra an toàn đạt và khớp bản nháp hiện tại.',
      'Tài khoản quản trị đang hoạt động xác nhận thao tác công khai thật.',
      'Người vận hành đã hiểu công khai thật sẽ thay đổi website.',
    ],
    fields: {
      version: 'Mã phiên bản',
      schema: 'Định dạng nội dung',
      status: 'Trạng thái',
      publishedAt: 'Thời điểm bản ghi tham chiếu',
      createdAt: 'Thời điểm tạo',
      note: 'Ghi chú',
    },
    readinessFields: {
      publicBundle: 'Bản ghi tham chiếu',
      canonicalJson: 'Nội dung website đang dùng',
      savedDraft: 'Bản nháp đã lưu',
      dirtyState: 'Trạng thái dirty',
      validation: 'Kiểm tra nội dung',
      dryRun: 'Kiểm tra an toàn',
      mainTabWrite: 'Ghi dữ liệu từ tab này',
      publishGate: 'Bước công khai thật',
      history: 'Lịch sử / khôi phục',
    },
  },
  history: {
    title: 'Lịch sử phiên bản',
    countLabel: 'phiên bản',
    headers: ['Mã phiên bản', 'Định dạng nội dung', 'Trạng thái', 'Thời điểm công khai', 'Thời điểm tạo', 'Ghi chú', 'Thao tác'],
    empty: 'Chưa đọc được lịch sử phiên bản hoặc tài khoản chưa có quyền xem.',
    statusHelp: {
      published: 'Bản ghi tham chiếu có trạng thái đã công khai; chỉ dùng để đối chiếu, không phải nội dung website đang dùng.',
      archived: 'Đã lưu trữ: phiên bản cũ, dùng để đối chiếu khi cần.',
    },
    actions: ['Xem chi tiết — sẽ bật sau', 'So sánh — sẽ bật sau'],
    actionDisabled: 'Chưa bật ở chế độ chỉ xem',
    lockedNotice: 'Bảng này chỉ là tham chiếu cũ. Lịch sử vận hành và bản xem trước phiên bản là nơi dùng để khôi phục.',
  },

  rollbackHistoryOperator: {
    highRiskTitle: 'Khôi phục phiên bản là thao tác quan trọng',
    highRiskIntro: 'Lịch sử phiên bản có thể khôi phục website khi tài khoản admin active thực hiện đủ bước. Đây không phải màn chỉ xem thuần.',
    highRiskNotes: [
      'Mở màn này hoặc tải lại lịch sử chỉ để xem, không tự khôi phục.',
      'Xem trước chỉ đọc bản đã chọn, không thay đổi website.',
      'Kiểm tra khôi phục chạy qua bộ kiểm tra trên server và vẫn chưa khôi phục thật.',
      'Khôi phục phiên bản sẽ thay đổi website và luôn cần xác nhận rõ.',
    ],
    readinessTitle: 'Checklist trước khi khôi phục',
    readinessIntro: 'Các mục dưới đây giúp kiểm tra xem đã đủ điều kiện khôi phục chưa.',
    disabledReasonsTitle: 'Chưa thể khôi phục vì',
    reasonHelp: 'Nhập lý do rõ ràng, ví dụ: khôi phục bản sạch sau lỗi nội dung hoặc theo yêu cầu vận hành.',
    serverSourceWarning: 'Khôi phục đã có bước kiểm tra trên server và vẫn cần xác nhận rõ trước khi thay đổi website.',
    previewNote: 'Xem trước chỉ đọc bản đã chọn và không thay đổi website.',
    dryRunNote: 'Kiểm tra khôi phục chỉ kiểm tra điều kiện, chưa thay đổi website.',
    realRollbackNote: 'Khôi phục phiên bản sẽ thay đổi website nếu qua đủ điều kiện và xác nhận hai bước.',
    actions: {
      refresh: 'Làm mới lịch sử phiên bản. Chỉ xem danh sách, không khôi phục.',
      preview: 'Xem trước bản đã chọn. Chỉ đọc dữ liệu.',
      select: 'Chọn bản này để khôi phục.',
      dryRun: 'Kiểm tra khôi phục cho bản đã chọn. Website chưa thay đổi.',
      reason: 'Lý do khôi phục để ghi lại cho người vận hành.',
      rollback: 'Khôi phục phiên bản đã chọn. Website sẽ thay đổi nếu xác nhận đủ bước.',
    },
  },

  cleanup: {
    operatorSteps: {
      title: 'Dọn phiên bản & backup cũ',
      subtitle: 'Quét & kiểm tra bản cũ ngoài vùng giữ lại, chọn đúng một bản, rồi xác nhận xóa có kiểm soát.',
      note: 'Mặc định giữ lại 10 nhóm phiên bản mới nhất. Số lượng có thể dọn không phải là 10 bản mới nhất.',
      steps: [
        'Quét & kiểm tra bản cũ.',
        'Chọn một phiên bản hoặc bản sao lưu cũ.',
        'Bấm Xóa bản đã chọn nếu bản đó đủ điều kiện.',
        'Xác nhận bằng popup tiếng Việt.',
      ],
    },
    title: 'Dọn phiên bản & backup cũ',
    status: 'Giữ lại 10 nhóm phiên bản mới nhất',
    intro: 'Màn này ưu tiên dọn phiên bản, bản sao lưu và bản sao khôi phục cũ trong kho nội dung website. Ảnh/video xử lý ở màn Ảnh & video.',
    adminOnly: 'Chỉ quản trị viên đang hoạt động được quét, kiểm tra và xóa bản cũ có kiểm soát.',
    controls: {
      scope: 'Phạm vi',
      retentionDays: 'Số ngày giữ lại',
      keepLastVersions: 'Giữ lại 10 nhóm phiên bản mới nhất',
      scan: 'Chỉ quét danh sách',
      dryRun: 'Quét & kiểm tra bản cũ',
      scanning: 'Đang quét...',
      dryRunning: 'Đang quét & kiểm tra...',
      safeDelete: 'Xóa bản đã chọn',
      safeDeleting: 'Đang xóa bản...',
    },
    scopes: {
      all: 'Tất cả',
      media: 'Ảnh/video',
      versions: 'Phiên bản & backup cũ',
      drafts: 'Bản nháp',
    },
    summaryTitle: 'Tổng quan kết quả',
    itemsTitle: 'Danh sách bản cũ',
    noResult: 'Chưa có kết quả. Hãy bấm “Quét & kiểm tra bản cũ”.',
    deleteDisabled: 'Xóa thô đang tắt. Màn này chỉ xóa đúng một bản/backup cũ đã chọn sau khi server tự kiểm tra lại an toàn.',
    safeDeleteTitle: 'Xóa bản đã chọn',
    safeDeleteWarning: 'Thao tác này xóa file khỏi kho nội dung website và không thể hoàn tác từ CMS. Server chỉ xóa đúng bản đã chọn sau khi tự kiểm tra lại.',
    safeDeleteGraphIncomplete: 'Không thể xóa vì danh sách kiểm tra chưa đầy đủ.',
    safeDeleteNoEligible: 'Không có bản cũ nào có thể dọn.',
    safeDeleteNoCandidates: 'Không có bản cũ nào đủ điều kiện dọn trong lần kiểm tra hiện tại.',
    safeDeleteCandidateMissing: 'Có bản có thể xóa trong tổng quan nhưng danh sách chưa hiển thị đầy đủ. Nút xóa đang khóa để tránh thao tác khi chưa thấy rõ bản sẽ xử lý.',
    safeDeleteLimited: 'Danh sách kiểm tra có dấu hiệu bị giới hạn hoặc chưa tải đầy đủ. Nút xóa đang khóa để tránh thao tác khi chưa thấy rõ bản sẽ xử lý.',
    safeDeleteConfirmHelp: 'Xác nhận bằng popup tiếng Việt trước khi xóa bản đã chọn.',
    headers: ['Kho', 'Đường dẫn', 'Loại', 'Lý do', 'Có thể dọn', 'Dung lượng', 'Đang dùng trên website', 'Ghi nhận trong lịch sử'],
    filters: {
      all: 'Tất cả kết luận',
      active: 'Đang dùng',
      unreferenced: 'Chưa thấy nơi dùng',
      missing_metadata: 'Thiếu dòng quản lý',
      missing_object: 'Thiếu tệp',
      unsafe_to_delete: 'Không an toàn để xóa',
      referenced_by_version: 'Đang nằm trong phiên bản/bản sao',
      discarded_draft_only: 'Chỉ nằm trong bản nháp đã bỏ',
      version_only_old: 'Phiên bản cũ',
      backup_old: 'Bản sao lưu cũ',
      rollback_backup_old: 'Bản sao khôi phục cũ',
    },
  },

  settings: {
    operatorSteps: {
      title: 'Các bước chỉnh Thông tin website',
      subtitle: 'Cập nhật thông tin đơn vị, liên hệ và ngôn ngữ trong một workspace. Lưu vào CMS chưa làm đổi website public.',
      note: 'Website public chỉ đổi sau luồng công khai riêng.',
      steps: [
        'Mở chỉnh sửa và cập nhật thông tin cần đổi.',
        'Lưu vào CMS khi kiểm tra đạt.',
        'Công khai bản đã lưu ở luồng riêng khi muốn website public thay đổi.',
        'Mở website để kiểm tra.',
      ],
    },
    websiteTitle: 'Thông tin website',
    workspaceIntro: 'Cập nhật thông tin đơn vị, liên hệ và ngôn ngữ. Lưu vào CMS chưa làm đổi website public.',
    publicBoundaryNote: 'Lưu vào CMS chưa làm đổi website public. Website chỉ đổi sau luồng công khai riêng.',
    logoDraftNote: 'Logo URL hiện giữ ở mức kỹ thuật trong CMS; chưa xác nhận public header đọc trực tiếp field này.',
    adminTitle: 'Trạng thái quản trị',
    basicTitle: 'Thông tin cơ bản',
    identityTitle: 'Hiển thị website',
    technicalTitle: 'Thông tin kỹ thuật',
    siteMissing: 'Chưa đọc được thông tin website hoặc tài khoản chưa có quyền xem.',
    websiteFields: {
      siteTitle: 'Tên website',
      organization: 'Đơn vị quản lý',
      address: 'Địa chỉ',
      phone: 'Điện thoại',
      fax: 'Số fax',
      email: 'Thư điện tử',
      logoUrl: 'Logo URL kỹ thuật',
      status: 'Trạng thái bản ghi CMS',
      language: 'Ngôn ngữ mặc định',
    },
    adminFields: {
      role: 'Vai trò hiện tại',
      viewMode: 'Chế độ xem',
      writeActions: 'Chức năng chỉnh sửa',
      connection: 'Kết nối dữ liệu',
    },
    missingEmail: 'Chưa khai báo thư điện tử.',
    cmsStatusNote: 'Đây là trạng thái bản ghi quản trị trong CMS, không phải trạng thái phiên bản website đang chạy.',
    logoNote: 'Logo URL là dữ liệu kỹ thuật trong bản ghi CMS; chưa xác nhận đang dùng trực tiếp trên public header.',
    notice: 'Chỉ màn Thông tin website, Cổng vào triển lãm và Khu vực đầu trang của Trang chủ được bật chỉnh sửa bản nháp ở bước này. Các khu vực khác vẫn đang chỉ xem.',
    edit: {
      title: 'Chỉnh sửa thông tin website',
      enabledScope: 'Chỉ bật chỉnh sửa Thông tin website',
      readOnlyScope: 'Các khu vực khác vẫn đang chỉ xem.',
      button: 'Chỉnh sửa thông tin',
      cancel: 'Hủy',
      reset: 'Đặt lại thay đổi',
      focusedNote: 'Đang chỉnh ở panel bên dưới.',
      save: 'Lưu vào CMS',
      saving: 'Đang lưu...',
      dirty: 'Có thay đổi chưa lưu.',
      success: 'Đã lưu vào CMS. Website public chưa thay đổi cho tới khi công khai.',
      error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
      safeNote: 'Lưu vào CMS chưa làm đổi website public.',
      leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
      noPermission: 'Tài khoản hiện tại chỉ được xem thông tin website.',
      logoReadonly: 'Chọn logo chỉ cập nhật field kỹ thuật logo_url trong bản nháp đang chỉnh. Bấm Lưu vào CMS mới ghi lại; website public chưa đổi.',
      statusReadonly: 'Trạng thái bản ghi CMS chỉ xem ở bước này.',
      fields: {
        site_title: 'Tên website',
        organization_name: 'Đơn vị quản lý',
        address: 'Địa chỉ',
        phone: 'Điện thoại',
        fax: 'Số fax',
        email: 'Thư điện tử',
        default_language: 'Ngôn ngữ mặc định',
        logo_url: 'Logo URL kỹ thuật',
        site_status: 'Trạng thái bản ghi CMS',
      },
      placeholders: {
        site_title: 'Nhập tên website',
        organization_name: 'Nhập tên đơn vị quản lý',
        address: 'Nhập địa chỉ',
        phone: 'Nhập số điện thoại',
        fax: 'Nhập số fax',
        email: 'name@example.com',
      },
      errors: {
        siteTitleRequired: 'Tên website không được để trống.',
        organizationRequired: 'Đơn vị quản lý không được để trống.',
        emailInvalid: 'Thư điện tử không đúng định dạng.',
        languageInvalid: 'Ngôn ngữ mặc định không hợp lệ.',
        logoInvalid: 'Đường dẫn logo không an toàn hoặc không thuộc nguồn được phép.',
      },
      warnings: {
        addressShort: 'Địa chỉ đang khá ngắn. Vui lòng kiểm tra lại trước khi công khai.',
        siteTitleLong: 'Tên website khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
        organizationLong: 'Tên đơn vị quản lý khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
        logoMissing: 'Chưa có logo URL hợp lệ. Đây là field kỹ thuật và chưa xác nhận đang dùng trên public header.',
      },
    },
  },
  maps: {
    roles: {
      admin: 'Quản trị viên',
      editor: 'Biên tập viên',
      unknown: 'Chưa rõ vai trò',
    },
    active: {
      true: 'Đang hoạt động',
      false: 'Không hoạt động',
    },
    status: {
      published: 'Đang công khai',
      archived: 'Đã lưu trữ',
      draft: 'Bản nháp',
      ok: 'Đang hoạt động',
      active: 'Đang bật',
      inactive: 'Đang tắt',
    },
    rooms: {
      indoor: 'Phòng trưng bày',
      outdoor: 'Không gian ngoài trời',
    },
    types: {
      artwork: 'Tác phẩm',
      video: 'Video',
      image: 'Hình ảnh',
      document: 'Tư liệu',
    },
    visible: {
      true: 'Đang hiển thị',
      false: 'Đang ẩn',
    },
    featured: {
      true: 'Có',
      false: 'Không',
    },
    warning: {
      empty: 'Không có',
      present: 'Có cảnh báo',
    },
    writeActions: {
      locked: 'Chưa bật chỉnh sửa',
      enabled: 'Đã bật chỉnh sửa',
      siteSettingsOnly: 'Chỉ bật Thông tin website',
      siteSettingsAndGate: 'Chỉ bật Thông tin website và Cổng vào',
    },
    viewMode: {
      on: 'Đang bật',
      off: 'Đang tắt',
    },
    languages: {
      vi: 'Tiếng Việt',
      en: 'Tiếng Anh',
    },
  },
  notices: {
    readOnly: 'Bạn đang xem dữ liệu nội dung. Chức năng chỉnh sửa sẽ được bật ở bước sau.',
    publicSafe: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website không bị ảnh hưởng trong bước này.',
    loading: 'Đang tải dữ liệu nội dung...',
    accessDeniedTitle: 'Tài khoản chưa được cấp quyền quản trị nội dung',
    accessDeniedFallback: 'Tài khoản chưa có hồ sơ quyền truy cập hoặc chưa được cấp quyền xem trang quản trị nội dung.',
    configWarningTitle: 'Chưa cấu hình kết nối dữ liệu cho trang quản trị nội dung',
    configWarningBody: 'Hãy cập nhật thông tin kết nối trong cấu hình trang quản trị. Không dùng khóa quyền cao trong trình duyệt.',
  },
});

export function getPageCopy(key) {
  return ADMIN_COPY.pages[key] || ADMIN_COPY.pages.dashboard;
}

export function getRoleLabel(role) {
  return ADMIN_COPY.maps.roles[role] || ADMIN_COPY.maps.roles.unknown;
}

export function getActiveLabel(isActive) {
  return isActive ? ADMIN_COPY.maps.active.true : ADMIN_COPY.maps.active.false;
}

export function getStatusLabel(status) {
  const key = String(status || '').toLowerCase();
  return ADMIN_COPY.maps.status[key] || status || '—';
}

export function getRoomLabel(roomKey) {
  return ADMIN_COPY.maps.rooms[roomKey] || roomKey || '—';
}

export function getContentTypeLabel(type) {
  return ADMIN_COPY.maps.types[type] || type || '—';
}

export function getVisibleLabel(value) {
  return value ? ADMIN_COPY.maps.visible.true : ADMIN_COPY.maps.visible.false;
}

export function getFeaturedLabel(value) {
  return value ? ADMIN_COPY.maps.featured.true : ADMIN_COPY.maps.featured.false;
}

export function getWarningLabel(value) {
  return value ? ADMIN_COPY.maps.warning.present : ADMIN_COPY.maps.warning.empty;
}

export function getLanguageLabel(language) {
  const key = String(language || '').toLowerCase();
  return ADMIN_COPY.maps.languages[key] || language || '—';
}

export function getFriendlyNote(note) {
  const text = String(note || '').trim();
  if (!text) return '—';
  if (text === 'Published by V6.11.20 backend foundation script.') {
    return 'Tạo bằng công cụ khởi tạo dữ liệu.';
  }
  return text;
}
