export const ADMIN_COPY = Object.freeze({
  app: {
    title: 'Quản trị nội dung',
    subtitle: 'Trang xem và quản lý nội dung website triển lãm 3D',
    shortSubtitle: 'Triển lãm 3D',
    eyebrow: 'Quản trị nội dung',
    loginEyebrow: 'Đăng nhập quản trị',
    brandEyebrow: 'Không gian triển lãm',
    brandTitle: 'Trung tâm Văn hóa và Triển lãm',
    logoMark: 'ND',
    sidebarFooterTitle: 'Trang quản trị',
  },
  login: {
    fields: {
      email: 'Thư điện tử',
      password: 'Mật khẩu',
    },
    placeholders: {
      email: 'nguoiquantri@example.com',
      password: '••••••••',
    },
    submit: 'Đăng nhập',
    submitting: 'Đang đăng nhập...',
  },
  navGroups: [
    {
      key: 'overview',
      items: [{ key: 'dashboard', label: 'Tổng quan' }],
    },
    {
      key: 'website',
      label: 'Nội dung website',
      items: [
        { key: 'home', label: 'Trang chủ' },
        { key: 'gate', label: 'Cổng vào triển lãm' },
      ],
    },
    {
      key: 'gallery3d',
      label: 'Triển lãm 3D',
      items: [
        { key: 'staticDraft', label: 'Nội dung phòng 3D' },
        { key: 'media', label: 'Ảnh & video' },
      ],
    },
    {
      key: 'operations',
      label: 'Vận hành',
      items: [
        { key: 'publish', label: 'Công khai nội dung' },
        { key: 'history', label: 'Lịch sử phiên bản' },
        { key: 'cleanup', label: 'Dọn dẹp lưu trữ' },
      ],
    },
    {
      key: 'settings',
      label: 'Cấu hình',
      items: [{ key: 'settings', label: 'Thông tin website' }],
    },
  ],
  nav: [
    { key: 'dashboard', label: 'Tổng quan' },
    { key: 'home', label: 'Trang chủ' },
    { key: 'gate', label: 'Cổng vào triển lãm' },
    { key: 'media', label: 'Ảnh & video' },
    { key: 'staticDraft', label: 'Nội dung phòng 3D' },
    { key: 'publish', label: 'Công khai nội dung' },
    { key: 'history', label: 'Lịch sử phiên bản' },
    { key: 'cleanup', label: 'Dọn dẹp lưu trữ' },
    { key: 'settings', label: 'Thông tin website' },
  ],
  globalEdit: {
    cleanEditing: 'Đang chỉnh sửa — chưa có thay đổi.',
    noChanges: 'Chưa có thay đổi để lưu.',
    cancel: 'Hủy',
    reset: 'Đặt lại thay đổi',
    resetConfirm: 'Đặt lại các thay đổi chưa lưu trong form này?',
    resetSuccess: 'Đã đặt lại thay đổi chưa lưu.',
    leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
    savingBlocked: 'Đang lưu bản nháp, vui lòng chờ hoàn tất.',
    mobileSafeMode: 'Thiết bị này đang ở chế độ xem an toàn. Hãy dùng tablet hoặc máy tính để chỉnh sửa nội dung.',
    draftShort: 'Lưu tại CMS, chưa đổi website public.',
    technicalLocked: 'Mã kỹ thuật và đường dẫn đang khóa để tránh lệch dữ liệu.',
    mediaReadonly: 'Media chỉ xem. Thay media ở bước Media Upload sau.',
  },
  badges: {
    viewMode: 'Chế độ xem',
    lockedEditing: 'Chưa bật toàn CMS',
    editingEnabled: 'Đã bật chỉnh sửa',
  },
  help: {
    viewMode: {
      title: 'Chế độ xem là gì?',
      paragraphs: [
        'Bạn đang xem dữ liệu nội dung của website triển lãm.',
        'Ở chế độ này, mọi thao tác chỉ để xem thông tin, chưa làm thay đổi website.',
      ],
      listTitle: 'Bạn chưa thể:',
      bullets: [
        'Sửa phần lớn nội dung',
        'Tải ảnh hoặc video',
        'Công khai nội dung mới',
        'Khôi phục phiên bản cũ',
      ],
      footer: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website đang chạy không bị ảnh hưởng.',
      button: 'Đã hiểu',
    },
    lockedEditing: {
      title: 'Vì sao chưa chỉnh sửa được?',
      paragraphs: [
        'Chức năng chỉnh sửa đang được khóa cho phần lớn nội dung để bảo vệ dữ liệu.',
        'Riêng màn Thông tin website, Cổng vào triển lãm và Khu vực đầu trang của Trang chủ có thể được bật chỉnh sửa bản nháp khi đủ quyền.',
      ],
      listTitle: 'Các chức năng sẽ được bật ở bước sau:',
      bullets: [
        'Chỉnh sửa thông tin website ở phạm vi hẹp',
        'Chỉnh sửa chữ hiển thị của Cổng vào triển lãm',
        'Chỉnh sửa Khu vực đầu trang của Trang chủ',
        'Chỉnh sửa tác phẩm',
        'Tải ảnh/video',
        'Kiểm tra và công khai nội dung',
      ],
      footer: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website public không bị ảnh hưởng trong bước này.',
      button: 'Đã hiểu',
    },
  },
  pages: {
    dashboard: {
      title: 'Tổng quan',
      subtitle: 'Theo dõi nội dung đang hiển thị trên website triển lãm.',
    },
    home: {
      title: 'Trang chủ',
      subtitle: 'Kiểm tra nội dung hiển thị ở trang giới thiệu đầu tiên của website triển lãm.',
    },
    gate: {
      title: 'Cổng vào triển lãm',
      subtitle: 'Kiểm tra nội dung màn chọn không gian trước khi người xem vào tham quan.',
    },
    media: {
      title: 'Ảnh & video',
      subtitle: 'Quản lý ảnh, video và poster của nội dung triển lãm. Chức năng tải tệp sẽ được bật ở bước sau.',
    },
    staticDraft: {
      title: 'Nội dung phòng 3D',
      subtitle: 'Chỉnh nội dung, hình ảnh và video cho các phòng 3D. Website public chỉ thay đổi sau khi công khai nội dung.',
    },
    publish: {
      title: 'Công khai nội dung',
      subtitle: 'Kiểm tra phiên bản nội dung đang công khai trên website.',
    },
    history: {
      title: 'Lịch sử phiên bản',
      subtitle: 'Xem các phiên bản nội dung đã từng được công khai hoặc lưu trữ.',
    },
    cleanup: {
      title: 'Dọn dẹp lưu trữ',
      subtitle: 'Quét và dry-run phân loại media, version, backup. V6.12-A1 chưa xóa dữ liệu.',
    },
    settings: {
      title: 'Thông tin website',
      subtitle: 'Xem và chỉnh sửa bản nháp thông tin website ở phạm vi an toàn.',
    },
  },
  staticDraft: {
    mainTitle: 'Nội dung phòng 3D',
    statusReady: 'Đang sửa bản nháp',
    warning: 'Màn này chỉnh nội dung, ảnh và video cho các item đã có trong phòng 3D. Website public chỉ thay đổi sau khi công khai nội dung.',
    load: 'Tải nội dung đang công khai',
    loading: 'Đang tải nội dung...',
    reset: 'Hoàn tác về lúc tải gần nhất',
    export: 'Xuất JSON kỹ thuật',
    copy: 'Sao chép JSON kỹ thuật',
    dirty: 'Có thay đổi chưa lưu',
    clean: 'Đã lưu / chưa có thay đổi',
    source: 'Nguồn nội dung',
    room: 'Phòng',
    item: 'Tác phẩm / item',
    fieldsTitle: 'Thông tin nội dung và media',
    previewTitle: 'Xem trước media',
    validationTitle: 'Kiểm tra trước khi công khai',
    exportTitle: 'Nâng cao',
    saveTitle: 'Quản lý bản nháp',
    saveDraft: 'Lưu bản nháp',
    saveAsNew: 'Lưu thành bản nháp mới',
    savedDrafts: 'Bản nháp đã lưu',
    notPublished: 'Nội dung chưa được công khai lên website.',
    noBaseline: 'Chưa tải nội dung hiện tại.',
    noItem: 'Chưa chọn tác phẩm / item.',
    sourceRemote: 'remote',
    sourceFallback: 'fallback',
    sourceLocal: 'local',
    sourceUnknown: 'chưa rõ',
  },
  dashboard: {
    websiteLink: 'Xem website',
    status: {
      title: 'Trạng thái website',
      currentVersion: 'Phiên bản website đang công khai',
      cmsRecordStatus: 'Trạng thái bản ghi CMS',
      dataSource: 'Dữ liệu CMS đang đọc',
      readOnlyMode: 'Chế độ hiện tại',
      publishedAt: 'Thời điểm công khai',
      website: 'Website đang hoạt động',
      safety: 'Chế độ xem an toàn',
      active: 'Đang hoạt động',
      safe: 'Chỉ xem, không thay đổi dữ liệu',
      readOnly: 'Chỉ xem',
      sourceNote: 'Website public dùng nội dung đã công khai từ CMS JSON. Nếu CMS public JSON chưa đọc được, Tổng quan dùng DB catalog làm dự phòng.',
      canonicalSource: 'Nguồn chính: CMS public JSON',
      fallbackSource: 'Nguồn dự phòng: DB catalog',
    },
    quickActions: {
      title: 'Đi nhanh',
      actions: [
        { key: 'home', label: 'Kiểm tra Trang chủ', note: 'Nội dung trang giới thiệu đầu tiên' },
        { key: 'gate', label: 'Kiểm tra Cổng vào triển lãm', note: 'Màn chọn không gian tham quan' },
        { key: 'staticDraft', label: 'Mở Nội dung phòng 3D', note: 'Chỉnh nội dung, ảnh và video cho các phòng 3D' },
      ],
      website: {
        label: 'Xem website public',
        note: 'Mở trang đang chạy trong tab mới',
      },
    },
    metrics: {
      title: 'Số liệu nội dung',
      rooms: 'Không gian',
      artworks: 'Tác phẩm',
      indoor: 'Trong phòng',
      outdoor: 'Ngoài trời',
      media: 'Ảnh/video',
      featured: 'Tác phẩm tiêu biểu',
    },
    cards: {
      currentContent: {
        label: 'Nội dung đang công khai',
        emptyNote: 'Chưa có nội dung công khai',
      },
      connection: {
        label: 'Kết nối dữ liệu',
        ok: 'Đang hoạt động',
        warning: 'Cần kiểm tra',
        okNote: 'Đọc dữ liệu thành công',
        warningNote: 'Một số nội dung chưa đọc được',
      },
    },
    tasks: {
      title: 'Việc cần chú ý',
      mediaEmpty: 'Thư viện ảnh/video hiện chưa có tệp nào.',
      warningAction: 'Mở Nội dung phòng 3D',
      locked: 'Chỉ một số màn được chỉnh sửa bản nháp. Upload, công khai và khôi phục vẫn đang khóa.',
      publicSafe: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website public không bị ảnh hưởng trong bước này.',
      warningEmpty: 'Hiện chưa có cảnh báo nội dung cần xử lý.',
      canonicalWarningHint: 'Bấm để mở Nội dung phòng 3D. Các cảnh báo bên dưới được tính từ nội dung CMS public JSON đang công khai.',
      fallbackWarningHint: 'Bấm để mở Nội dung phòng 3D. Dashboard đang dùng DB catalog làm nguồn dự phòng. Các cảnh báo này chỉ là dữ liệu tham chiếu.',
      warningHint: 'Bấm để mở Nội dung phòng 3D. Các cảnh báo DB catalog chỉ là dữ liệu tham chiếu, website public đổi qua bản nháp CMS.',
    },
    safety: {
      title: 'Trạng thái an toàn',
      body: 'Bạn đang xem nội dung ở chế độ chỉ xem. Chưa có thao tác nào làm thay đổi website đang chạy.',
    },
    panels: {
      siteSettings: 'Thông tin website',
      contentPublished: 'Phiên bản website đang công khai',
    },
  },
  contentViews: {
    home: {
      sourceTitle: 'Dữ liệu Trang chủ đang đọc',
      emptyTitle: 'Chưa đọc được dữ liệu Trang chủ từ CMS',
      emptyBody: 'Kiểm tra bảng index_sections hoặc quyền xem dữ liệu. Không có nội dung giả được tạo trong màn này.',
      publicLink: 'Mở Trang chủ public',
      focusedEditNote: 'Đang chỉnh ở panel bên dưới.',
      sectionLabels: {
        hero: 'Khu vực đầu trang',
        experience: 'Khu vực trải nghiệm',
        guide: 'Hướng dẫn tham quan',
        contact: 'Thông tin liên hệ',
      },
      fields: {
        eyebrow: 'Nhãn nhỏ',
        title: 'Tiêu đề',
        subtitle: 'Tiêu đề phụ',
        lead: 'Mô tả ngắn',
        body: 'Nội dung mô tả',
        cta: 'Nút/CTA',
        media: 'Ảnh/video giới thiệu',
        items: 'Nội dung con',
        status: 'Trạng thái hiển thị',
        updatedAt: 'Cập nhật gần nhất',
      },
      presentation: {
        mainContent: 'Nội dung chính',
        cta: 'Nút/CTA',
        media: 'Ảnh/video giới thiệu',
        childItems: 'Danh sách nội dung con',
        statusInfo: 'Trạng thái nội dung',
        missingFields: 'Một số trường chưa khai báo',
        declaredData: 'Đã khai báo dữ liệu',
        dataFields: 'Trường dữ liệu',
        notDeclared: 'Chưa khai báo',
        buttonLabel: 'Nhãn nút',
        path: 'Đường dẫn',
        actionType: 'Loại hành động',
        caption: 'Chú thích',
        videoPath: 'Đường dẫn video',
        imagePath: 'Đường dẫn ảnh',
        fileType: 'Loại tệp',
        itemTitleFallback: 'Mục nội dung',
      },
      contactSource: {
        title: 'Nguồn dữ liệu liên hệ chính thức',
        notice: 'Thông tin liên hệ chính thức được quản lý tại Thông tin website.',
        detail: 'Địa chỉ, điện thoại, fax và email không chỉnh tại section này để tránh lệch dữ liệu.',
        mirrorTitle: 'Dữ liệu liên hệ đang dùng',
        sectionDataTitle: 'Nội dung section Contact hiện tại',
        openSettings: 'Mở Thông tin website',
        settingsHint: 'Nếu cần cập nhật thông tin liên hệ, hãy chỉnh tại Thông tin website.',
        readonly: 'Contact section đang ở chế độ chỉ xem.',
        missing: 'Chưa khai báo',
        fields: {
          organization: 'Đơn vị quản lý',
          address: 'Địa chỉ',
          phone: 'Điện thoại',
          fax: 'Fax',
          email: 'Email',
        },
      },
      safety: 'Màn này chỉ chỉnh sửa bản nháp cho Khu vực đầu trang. Các phần Trang chủ khác vẫn đang chỉ xem.',
      edit: {
        title: 'Chỉnh sửa Khu vực đầu trang',
        enabledScope: 'Chỉ bật chỉnh sửa Khu vực đầu trang',
        readOnlyScope: 'Các phần Trang chủ khác vẫn đang chỉ xem.',
        button: 'Chỉnh sửa phần này',
        cancel: 'Hủy',
        reset: 'Đặt lại thay đổi',
        save: 'Lưu bản nháp',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website public chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website public.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị. Đường dẫn media, CTA link, thứ tự và trạng thái hiển thị được khóa ở bước này.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Trang chủ hoặc chưa bật chỉnh sửa Khu vực đầu trang.',
        mediaReadonlyNote: 'Đường dẫn media chỉ xem ở bước này. Chức năng thay media sẽ mở sau khi có Media Upload.',
        ctaReadonlyNote: 'Đường dẫn CTA chỉ xem ở bước này. Không tự tạo route/link mới.',
        itemsReadonlyNote: 'Không thể thêm, xóa hoặc sắp xếp lại mục con ở bước này.',
        technicalReadonlyNote: 'Thông tin kỹ thuật chỉ xem, không chỉnh trong bước này.',
        noCtaLabel: 'Chưa có nhãn CTA có thể chỉnh sửa trong dữ liệu gốc.',
        unsupportedItems: 'Cấu trúc nội dung con chưa hỗ trợ chỉnh sửa ở bước này.',
        emptyItems: 'Danh sách nội dung con đang trống.',
        groups: {
          main: 'Nội dung chính',
          media: 'Ảnh/video giới thiệu',
          items: 'Danh sách nội dung con',
          cta: 'Nút/CTA',
          technical: 'Thông tin kỹ thuật chỉ xem',
        },
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề',
          subtitle: 'Tiêu đề phụ',
          lead: 'Mô tả ngắn',
          body: 'Nội dung mô tả',
          mediaCaption: 'Chú thích media',
          mediaPath: 'Đường dẫn media',
          mediaType: 'Loại media',
          item: 'Mục',
          itemText: 'Nội dung mục',
          itemDescription: 'Mô tả mục',
          ctaLabel: 'Nhãn nút',
          ctaPath: 'Đường dẫn CTA',
          sectionKey: 'Mã section',
          sortOrder: 'Thứ tự hiển thị',
          visible: 'Trạng thái hiển thị',
          updatedAt: 'Cập nhật gần nhất',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề khu vực đầu trang',
          subtitle: 'Nhập tiêu đề phụ',
          lead: 'Nhập mô tả ngắn',
          body: 'Nhập nội dung mô tả',
          mediaCaption: 'Nhập chú thích ảnh/video',
          itemText: 'Nhập nội dung mục',
          itemDescription: 'Nhập mô tả mục',
          ctaLabel: 'Nhập nhãn nút',
        },
        errors: {
          titleRequired: 'Tiêu đề Khu vực đầu trang không được để trống.',
          sectionInvalid: 'Chỉ chỉnh sửa Khu vực đầu trang ở bước này.',
          mediaInvalid: 'Dữ liệu ảnh/video giới thiệu không hợp lệ.',
          itemsInvalid: 'Dữ liệu nội dung con không hợp lệ.',
          itemsCountChanged: 'Không thể thêm, xóa hoặc sắp xếp lại mục con ở bước này.',
        },
        warnings: {
          titleLong: 'Tiêu đề khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          leadLong: 'Mô tả ngắn khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          bodyLong: 'Nội dung mô tả khá dài. Nên kiểm tra lại trước khi công khai.',
          mediaCaptionEmpty: 'Chú thích media đang trống. Nên kiểm tra lại trước khi công khai.',
          mediaCaptionLong: 'Chú thích media khá dài. Nên rút gọn trước khi công khai.',
          itemTitleLong: 'Nội dung mục khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionLong: 'Mô tả mục khá dài. Nên kiểm tra lại cách hiển thị.',
          ctaLabelLong: 'Nhãn nút khá dài. Nên rút gọn trước khi công khai.',
        },
      },
      guideEdit: {
        title: 'Chỉnh sửa Hướng dẫn tham quan',
        enabledScope: 'Chỉ bật chỉnh sửa Hướng dẫn tham quan',
        readOnlyScope: 'Khu vực trải nghiệm và Thông tin liên hệ vẫn đang chỉ xem.',
        button: 'Chỉnh sửa phần này',
        cancel: 'Hủy',
        reset: 'Đặt lại thay đổi',
        save: 'Lưu bản nháp',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website public chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website public.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị của Hướng dẫn tham quan. CTA, media, thứ tự bước và dữ liệu kỹ thuật được khóa ở bước này.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Trang chủ hoặc chưa bật chỉnh sửa Hướng dẫn tham quan.',
        itemsReadonlyNote: 'Không thể thêm, xóa hoặc sắp xếp lại bước hướng dẫn ở bước này.',
        technicalReadonlyNote: 'Thông tin kỹ thuật chỉ xem, không chỉnh trong bước này.',
        unsupportedItems: 'Cấu trúc bước hướng dẫn chưa hỗ trợ chỉnh sửa ở bước này.',
        emptyItems: 'Danh sách bước hướng dẫn đang trống.',
        groups: {
          main: 'Nội dung chính',
          items: 'Danh sách bước hướng dẫn',
          technical: 'Thông tin kỹ thuật chỉ xem',
        },
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề',
          subtitle: 'Tiêu đề phụ',
          lead: 'Mô tả ngắn',
          body: 'Nội dung mô tả',
          step: 'Bước',
          stepText: 'Tên bước',
          stepTitle: 'Tên bước',
          stepDescription: 'Mô tả bước',
          readonlyMeta: 'Thông tin chỉ xem',
          sectionKey: 'Mã section',
          sortOrder: 'Thứ tự hiển thị',
          visible: 'Trạng thái hiển thị',
          itemCount: 'Số lượng bước',
          updatedAt: 'Cập nhật gần nhất',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề Hướng dẫn tham quan',
          subtitle: 'Nhập tiêu đề phụ',
          lead: 'Nhập mô tả ngắn',
          body: 'Nhập nội dung mô tả',
          stepText: 'Nhập tên bước',
          stepTitle: 'Nhập tên bước',
          stepDescription: 'Nhập mô tả bước',
        },
        errors: {
          titleRequired: 'Tiêu đề Hướng dẫn tham quan không được để trống.',
          sectionInvalid: 'Chỉ chỉnh sửa Hướng dẫn tham quan ở bước này.',
          itemsInvalid: 'Dữ liệu bước hướng dẫn không hợp lệ.',
          itemsCountChanged: 'Không thể thêm, xóa hoặc sắp xếp lại bước hướng dẫn ở bước này.',
        },
        warnings: {
          titleLong: 'Tiêu đề khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          leadLong: 'Mô tả ngắn khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          bodyLong: 'Nội dung mô tả khá dài. Nên kiểm tra lại trước khi công khai.',
          itemTitleLong: 'Tên bước khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionLong: 'Mô tả bước khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionEmpty: 'Mô tả bước đang trống, nên kiểm tra trước khi công khai.',
          itemsShort: 'Hướng dẫn có ít hơn 2 bước. Nên kiểm tra lại trước khi công khai.',
          itemsEmpty: 'Danh sách bước hướng dẫn đang trống.',
        },
      },

      experienceEdit: {
        title: 'Chỉnh sửa Khu vực trải nghiệm',
        enabledScope: 'Chỉ bật chỉnh sửa Khu vực trải nghiệm',
        readOnlyScope: 'Thông tin liên hệ vẫn đang chỉ xem.',
        button: 'Chỉnh sửa phần này',
        cancel: 'Hủy',
        reset: 'Đặt lại thay đổi',
        save: 'Lưu bản nháp',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website public chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website public.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị của Khu vực trải nghiệm. Mã phòng, đường dẫn tham quan, CTA và media được khóa ở bước này.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Trang chủ hoặc chưa bật chỉnh sửa Khu vực trải nghiệm.',
        itemsReadonlyNote: 'Không thể thêm, xóa hoặc sắp xếp lại card trải nghiệm ở bước này.',
        routeReadonlyNote: 'Mã phòng, nhãn nút vào phòng và đường dẫn tham quan chỉ xem ở bước này.',
        technicalReadonlyNote: 'Thông tin kỹ thuật chỉ xem, không chỉnh trong bước này.',
        unsupportedItems: 'Cấu trúc card trải nghiệm chưa hỗ trợ chỉnh sửa ở bước này.',
        emptyItems: 'Danh sách card trải nghiệm đang trống.',
        groups: {
          main: 'Nội dung chính',
          items: 'Danh sách card trải nghiệm',
          technical: 'Thông tin kỹ thuật chỉ xem',
        },
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề',
          subtitle: 'Tiêu đề phụ',
          lead: 'Mô tả ngắn',
          body: 'Nội dung mô tả',
          card: 'Card',
          cardText: 'Tên card',
          cardTitle: 'Tên card',
          cardDescription: 'Mô tả card',
          roomKey: 'Mã phòng',
          ctaLabel: 'Nhãn nút vào phòng',
          route: 'Đường dẫn tham quan',
          readonlyMeta: 'Thông tin chỉ xem',
          sectionKey: 'Mã section',
          sortOrder: 'Thứ tự hiển thị',
          visible: 'Trạng thái hiển thị',
          itemCount: 'Số lượng card',
          updatedAt: 'Cập nhật gần nhất',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề Khu vực trải nghiệm',
          subtitle: 'Nhập tiêu đề phụ',
          lead: 'Nhập mô tả ngắn',
          body: 'Nhập nội dung mô tả',
          cardText: 'Nhập tên card',
          cardTitle: 'Nhập tên card',
          cardDescription: 'Nhập mô tả card',
        },
        errors: {
          titleRequired: 'Tiêu đề Khu vực trải nghiệm không được để trống.',
          sectionInvalid: 'Chỉ chỉnh sửa Khu vực trải nghiệm ở bước này.',
          itemsInvalid: 'Dữ liệu card trải nghiệm không hợp lệ.',
          itemsCountChanged: 'Không thể thêm, xóa hoặc sắp xếp lại card trải nghiệm ở bước này.',
          protectedFieldChanged: 'Mã phòng, đường dẫn tham quan và nhãn nút vào phòng chỉ xem ở bước này.',
        },
        warnings: {
          titleLong: 'Tiêu đề khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          leadLong: 'Mô tả ngắn khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          bodyLong: 'Nội dung mô tả khá dài. Nên kiểm tra lại trước khi công khai.',
          itemTitleLong: 'Tên card khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionLong: 'Mô tả card khá dài. Nên kiểm tra lại cách hiển thị.',
          itemDescriptionEmpty: 'Mô tả card đang trống, nên kiểm tra trước khi công khai.',
          itemsShort: 'Khu vực trải nghiệm có ít hơn 2 card. Nên kiểm tra lại trước khi công khai.',
        },
      },
    },
    gate: {
      sourceTitle: 'Dữ liệu Cổng vào triển lãm đang đọc',
      emptyTitle: 'Chưa đọc được dữ liệu Cổng vào triển lãm từ CMS',
      emptyBody: 'Kiểm tra bảng gate_content hoặc quyền xem dữ liệu. Không có nội dung giả được tạo trong màn này.',
      publicLink: 'Mở Cổng vào triển lãm',
      mainInfo: 'Thông tin chính',
      roomsInfo: 'Lựa chọn không gian',
      fields: {
        eyebrow: 'Nhãn nhỏ',
        title: 'Tiêu đề cổng vào',
        description: 'Mô tả hướng dẫn',
        backLabel: 'Nhãn quay lại Trang chủ',
        active: 'Trạng thái sử dụng',
        updatedAt: 'Cập nhật gần nhất',
        roomTitle: 'Tên hiển thị',
        roomDescription: 'Mô tả không gian',
        roomCta: 'Nút bắt đầu tham quan',
        roomKey: 'Mã phòng kỹ thuật',
      },
      safety: 'Màn này chỉ xem nội dung hiển thị. Mã phòng, query vào phòng và luồng kỹ thuật không thay đổi ở đây.',
      edit: {
        title: 'Chỉnh sửa Cổng vào triển lãm',
        enabledScope: 'Chỉ bật chỉnh sửa Cổng vào triển lãm',
        readOnlyScope: 'Trang chủ và các khu vực khác vẫn đang chỉ xem.',
        button: 'Chỉnh sửa Cổng vào',
        cancel: 'Hủy',
        reset: 'Đặt lại thay đổi',
        save: 'Lưu bản nháp',
        saving: 'Đang lưu...',
        dirty: 'Có thay đổi chưa lưu.',
        success: 'Đã lưu bản nháp. Website public chưa thay đổi.',
        error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
        safeNote: 'Lưu tại CMS, chưa đổi website public.',
        leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
        noPermission: 'Tài khoản hiện tại chỉ được xem Cổng vào triển lãm.',
        jsonSafeNote: 'Bạn chỉ sửa chữ hiển thị. Mã phòng, query vào phòng, route và dữ liệu kỹ thuật được khóa ở bước này.',
        technicalTitle: 'Thông tin kỹ thuật chỉ xem',
        editorReadonly: 'editor_json không chỉnh ở bước này để tránh ảnh hưởng luồng kỹ thuật.',
        noCtaLabel: 'Chưa khai báo nhãn nút bắt đầu tham quan trong dữ liệu gốc.',
        fields: {
          eyebrow: 'Nhãn nhỏ',
          title: 'Tiêu đề cổng vào',
          description: 'Mô tả hướng dẫn',
          back_label: 'Nhãn quay lại Trang chủ',
          displayName: 'Tên hiển thị',
          roomDescription: 'Mô tả không gian',
          ctaLabel: 'Nhãn nút bắt đầu tham quan',
          roomKey: 'Mã phòng kỹ thuật',
          route: 'Đường dẫn tham quan',
          active: 'Trạng thái sử dụng',
        },
        groups: {
          main: 'Thông tin chính',
          indoor: 'Không gian trong nhà',
          outdoor: 'Không gian ngoài trời',
        },
        placeholders: {
          eyebrow: 'Nhập nhãn nhỏ',
          title: 'Nhập tiêu đề cổng vào',
          description: 'Nhập mô tả hướng dẫn',
          back_label: 'Ví dụ: Quay lại Trang chủ',
          displayName: 'Nhập tên hiển thị',
          roomDescription: 'Nhập mô tả không gian',
          ctaLabel: 'Ví dụ: Bắt đầu tham quan',
        },
        errors: {
          titleRequired: 'Tiêu đề cổng vào không được để trống.',
          roomsInvalid: 'Dữ liệu lựa chọn không gian không hợp lệ.',
          indoorMissing: 'Thiếu dữ liệu không gian trong nhà.',
          outdoorMissing: 'Thiếu dữ liệu không gian ngoài trời.',
          indoorInvalid: 'Dữ liệu không gian trong nhà không hợp lệ.',
          outdoorInvalid: 'Dữ liệu không gian ngoài trời không hợp lệ.',
          indoorNameRequired: 'Không gian trong nhà cần có tên hiển thị.',
          outdoorNameRequired: 'Không gian ngoài trời cần có tên hiển thị.',
        },
        warnings: {
          descriptionEmpty: 'Mô tả đang trống, nên kiểm tra trước khi công khai.',
          indoorDescriptionEmpty: 'Mô tả không gian trong nhà đang trống, nên kiểm tra trước khi công khai.',
          outdoorDescriptionEmpty: 'Mô tả không gian ngoài trời đang trống, nên kiểm tra trước khi công khai.',
          titleLong: 'Tiêu đề cổng vào khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          descriptionLong: 'Mô tả hướng dẫn khá dài. Nên kiểm tra lại trước khi công khai.',
          roomTitleLong: 'Tên hiển thị khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          roomDescriptionLong: 'Mô tả không gian khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
          ctaLong: 'Nhãn nút bắt đầu tham quan khá dài. Nên rút gọn trước khi công khai.',
        },
      },
    },
  },
  planningScreens: {
    home: {
      title: 'Trang chủ',
      status: 'Chỉ xem định hướng',
      intro: 'Đây là nơi sẽ quản lý nội dung hiển thị ở trang giới thiệu đầu tiên của website triển lãm.',
      sectionsTitle: 'Các phần sẽ quản lý',
      sections: [
        'Khu vực đầu trang',
        'Tiêu đề và mô tả giới thiệu',
        'Ảnh/video giới thiệu',
        'Nút vào triển lãm',
        'Khu vực trải nghiệm',
        'Hướng dẫn tham quan',
      ],
      noteTitle: 'Trạng thái hiện tại',
      note: 'Chức năng chỉnh sửa Trang chủ sẽ được bật ở bước sau. Hiện tại bạn chỉ xem định hướng nội dung.',
    },
    gate: {
      title: 'Cổng vào triển lãm',
      status: 'Không thay đổi luồng kỹ thuật',
      intro: 'Đây là nơi sẽ kiểm tra nội dung màn chọn không gian trước khi người xem vào tham quan.',
      sectionsTitle: 'Các phần sẽ quản lý',
      sections: [
        'Tiêu đề cổng vào',
        'Mô tả hướng dẫn chọn không gian',
        'Lựa chọn Không gian trong nhà',
        'Lựa chọn Không gian ngoài trời',
        'Nút bắt đầu tham quan',
        'Link quay lại trang chủ',
      ],
      noteTitle: 'Giới hạn an toàn',
      note: 'Màn này chỉ quản lý chữ và mô tả hiển thị. Mã phòng, đường dẫn vào phòng và luồng kỹ thuật không thay đổi ở đây.',
    },
  },
  media: {
    mainTitle: 'Thư viện ảnh & video',
    countLabel: 'tệp',
    emptyTitle: 'Chưa có media đã upload',
    intro: 'Chưa đọc được media nào từ nhật ký upload CMS.',
    body: 'Bạn vẫn có thể upload ảnh/video trong màn Nội dung phòng 3D hoặc Featured theo flow hiện có. Màn này chỉ để xem lại thư viện.',
    emptyBadge: 'Chỉ xem',
    readOnlyBadge: 'Read-only',
    uploadTypesTitle: 'Media sẽ xuất hiện ở đây sau khi upload từ',
    uploadTypes: ['Nội dung phòng 3D', 'Ảnh Featured trang chủ', 'Poster video', 'Video thuyết minh'],
    safeNotice: 'Màn này chỉ xem, tìm, lọc, preview và sao chép đường dẫn. Không upload, không xóa, không công khai nội dung.',
    readOnlyNotice: 'Website public không thay đổi khi bạn xem hoặc sao chép đường dẫn trong thư viện này.',
    metadataSource: 'Đọc từ nhật ký upload CMS',
    searchPlaceholder: 'Tìm theo tên file, đường dẫn, phòng, item hoặc URL',
    filters: {
      allKinds: 'Tất cả loại media',
      allUsage: 'Tất cả trạng thái sử dụng',
      allTargets: 'Tất cả nơi dùng',
    },
    kindLabels: {
      image: 'Ảnh',
      poster: 'Poster',
      video: 'Video',
      unknown: 'Media',
    },
    targetLabels: {
      room_artwork: 'Nội dung phòng 3D',
      index_featured: 'Featured trang chủ',
      unknown: 'Chưa rõ nơi dùng',
    },
    usageLabels: {
      public: 'Đang dùng trên website',
      draft: 'Đang dùng trong bản nháp',
      cms: 'Đang dùng trong CMS',
      none: 'Chưa thấy tham chiếu',
      insufficient: 'Không đủ dữ liệu để kết luận',
    },
    usageNotes: {
      none: 'Chưa thấy tham chiếu trong dữ liệu đã kiểm tra. Không đồng nghĩa media an toàn để xóa.',
      insufficient: 'Không đủ dữ liệu để kết luận media đang dùng hay không.',
    },
    referencesTitle: 'Tham chiếu tìm thấy',
    fields: {
      uploadTime: 'Ngày upload',
      fileSize: 'Dung lượng',
      target: 'Nơi dùng',
      room: 'Phòng',
      item: 'Item',
      field: 'Trường media',
      status: 'Trạng thái kỹ thuật từ nhật ký upload',
      url: 'Đường dẫn',
    },
    statusNote: 'Trạng thái này chỉ là metadata upload, không dùng để kết luận media đang dùng hay vòng đời media.',
    actions: {
      copyUrl: 'Sao chép đường dẫn',
      copied: 'Đã sao chép',
      copyFailed: 'Không sao chép được',
      goToReference: 'Đi tới nơi dùng',
    },
    referenceNavigationHint: 'Chỉ điều hướng trong CMS, không thay đổi website.',
    emptyFiltered: 'Không có media nào khớp bộ lọc hiện tại.',
    previewUnavailable: 'Không có preview an toàn cho media này.',
    previewError: 'Không tải được preview.',
    unsafeUrl: 'Đường dẫn media không thuộc nguồn được phép.',
    deleteDisabled: 'Không có nút xóa ở phase này. Media đang dùng hoặc chưa đủ dữ liệu phải đi qua cleanup dry-run riêng.',
    technicalTitle: 'Thông tin kỹ thuật, chỉ để đối chiếu',
    technicalRows: [
      ['Nơi lưu ảnh/video', 'Đã cấu hình', 'cms-media'],
      ['Nguồn danh sách thư viện', 'Đã cấu hình', 'cms_media_uploads'],
      ['Nơi lưu nội dung website', 'Đã cấu hình', 'cms-public'],
    ],
  },
  publish: {
    currentTitle: 'Nội dung đang công khai',
    noCurrent: 'Chưa đọc được nội dung đang công khai.',
    workflowTitle: 'Quy trình công khai nội dung',
    workflowStatus: 'Chưa bật thao tác',
    workflowSteps: ['Xem trước nội dung', 'Kiểm tra nội dung', 'Công khai lên website', 'Xác nhận website đã cập nhật'],
    actions: ['Xem trước nội dung', 'Kiểm tra nội dung', 'Công khai lên website'],
    notice: 'Hiện tại trang quản trị chỉ đang ở chế độ xem. Chức năng công khai nội dung sẽ được bật ở bước sau.',
    lockedNote: 'Chức năng này đang khóa để bảo vệ dữ liệu. Bạn chỉ có thể xem thông tin ở bước hiện tại.',
    publicLink: 'Mở website public để kiểm tra',
    requirementsTitle: 'Điều kiện để bật công khai nội dung',
    requirements: [
      'Có màn chỉnh sửa bản nháp an toàn.',
      'Có kiểm tra dữ liệu trước khi công khai.',
      'Có xem trước nội dung sẽ đưa lên website.',
      'Có bước xác nhận rõ ràng trước khi công khai.',
    ],
    fields: {
      version: 'Mã phiên bản',
      schema: 'Định dạng nội dung',
      status: 'Trạng thái',
      publishedAt: 'Thời điểm công khai',
      createdAt: 'Thời điểm tạo',
      note: 'Ghi chú',
    },
  },
  history: {
    title: 'Lịch sử phiên bản',
    countLabel: 'phiên bản',
    headers: ['Mã phiên bản', 'Định dạng nội dung', 'Trạng thái', 'Thời điểm công khai', 'Thời điểm tạo', 'Ghi chú', 'Thao tác'],
    empty: 'Chưa đọc được lịch sử phiên bản hoặc tài khoản chưa có quyền xem.',
    statusHelp: {
      published: 'Đang công khai: phiên bản website đang sử dụng.',
      archived: 'Đã lưu trữ: phiên bản cũ, dùng để đối chiếu khi cần.',
    },
    actions: ['Xem chi tiết — sẽ bật sau', 'So sánh — sẽ bật sau'],
    actionDisabled: 'Chưa bật ở chế độ chỉ xem',
    lockedNotice: 'Khôi phục phiên bản sẽ được bật ở bước sau, sau khi có kiểm tra và xác nhận an toàn.',
  },

  cleanup: {
    title: 'Media Library / Storage Cleanup',
    status: 'Scan/Dry-run + Safe Delete gated',
    intro: 'V6.12-A2 chỉ cho safe delete hẹp theo dry-run plan đã xác nhận. Không purge, không xóa cms-public.',
    adminOnly: 'Chỉ admin đang hoạt động được scan/dry-run/safe-delete cleanup.',
    controls: {
      scope: 'Phạm vi',
      retentionDays: 'Retention tối thiểu (ngày)',
      keepLastVersions: 'Giữ ít nhất số version gần nhất',
      scan: 'Quét lưu trữ',
      dryRun: 'Dry-run dọn dẹp',
      scanning: 'Đang quét...',
      dryRunning: 'Đang dry-run...',
      safeDelete: 'Xóa an toàn theo dry-run',
      safeDeleting: 'Đang xóa an toàn...',
    },
    scopes: {
      all: 'Tất cả',
      media: 'Media',
      versions: 'Version/backup',
      drafts: 'Draft',
    },
    summaryTitle: 'Tổng quan kết quả',
    itemsTitle: 'Danh sách phân loại',
    noResult: 'Chưa có kết quả. Hãy chạy Quét lưu trữ hoặc Dry-run.',
    deleteDisabled: 'Delete/purge tự do vẫn bị tắt. A2 chỉ có safeDelete hẹp nếu bật feature flag và confirm dry-run plan.',
    safeDeleteTitle: 'Xóa an toàn theo dry-run',
    safeDeleteWarning: 'Thao tác này sẽ xóa object trong Supabase Storage và không thể hoàn tác nếu không có backup.',
    safeDeleteGraphIncomplete: 'Không thể xóa vì dependency graph chưa đầy đủ.',
    safeDeleteNoEligible: 'Không có object eligible để xóa an toàn.',
    safeDeleteNoCandidates: 'Không có candidate đủ điều kiện Safe Delete trong dry-run hiện tại.',
    safeDeleteCandidateMissing: 'Có eligible item trong summary nhưng danh sách candidate A2 chưa được tải/hiển thị đầy đủ. Safe Delete đang bị khóa để tránh xác nhận khi chưa thấy rõ object sẽ xóa.',
    safeDeleteLimited: 'Danh sách candidate cleanup có dấu hiệu bị giới hạn hoặc chưa tải đầy đủ. Safe Delete đang bị khóa để tránh xác nhận khi chưa thấy rõ object sẽ xóa.',
    safeDeleteConfirmHelp: 'Nhập đúng cụm xác nhận để bật nút xóa an toàn.',
    headers: ['Bucket', 'Path', 'Loại', 'Phân loại', 'Eligible', 'Dung lượng', 'References', 'Lý do chặn'],
    filters: {
      all: 'Tất cả phân loại',
      active: 'Active',
      unreferenced: 'Unreferenced',
      missing_metadata: 'Missing metadata',
      missing_object: 'Missing object',
      unsafe_to_delete: 'Unsafe',
      version_only_old: 'Version cũ',
      backup_old: 'Backup cũ',
      rollback_backup_old: 'Rollback backup cũ',
    },
  },
  settings: {
    websiteTitle: 'Thông tin website',
    adminTitle: 'Trạng thái quản trị',
    basicTitle: 'Thông tin cơ bản',
    identityTitle: 'Nhận diện website',
    technicalTitle: 'Thông tin kỹ thuật',
    siteMissing: 'Chưa đọc được thông tin website hoặc tài khoản chưa có quyền xem.',
    websiteFields: {
      siteTitle: 'Tên website',
      organization: 'Đơn vị quản lý',
      address: 'Địa chỉ',
      phone: 'Điện thoại',
      fax: 'Số fax',
      email: 'Thư điện tử',
      logoUrl: 'Đường dẫn logo',
      status: 'Trạng thái bản ghi CMS',
      language: 'Ngôn ngữ mặc định',
    },
    adminFields: {
      role: 'Vai trò hiện tại',
      viewMode: 'Chế độ xem',
      writeActions: 'Chức năng chỉnh sửa',
      connection: 'Kết nối dữ liệu',
    },
    missingEmail: 'Chưa khai báo thư điện tử.',
    cmsStatusNote: 'Đây là trạng thái bản ghi quản trị trong CMS, không phải trạng thái phiên bản website public đang chạy.',
    logoNote: 'Đường dẫn logo chỉ để kiểm tra. Chức năng thay logo chưa được bật.',
    notice: 'Chỉ màn Thông tin website, Cổng vào triển lãm và Khu vực đầu trang của Trang chủ được bật chỉnh sửa bản nháp ở bước này. Các khu vực khác vẫn đang chỉ xem.',
    edit: {
      title: 'Chỉnh sửa thông tin website',
      enabledScope: 'Chỉ bật chỉnh sửa Thông tin website',
      readOnlyScope: 'Các khu vực khác vẫn đang chỉ xem.',
      button: 'Chỉnh sửa thông tin',
      cancel: 'Hủy',
      reset: 'Đặt lại thay đổi',
      focusedNote: 'Đang chỉnh ở panel bên dưới.',
      save: 'Lưu bản nháp',
      saving: 'Đang lưu...',
      dirty: 'Có thay đổi chưa lưu.',
      success: 'Đã lưu bản nháp. Website public chưa thay đổi.',
      error: 'Không thể lưu, vui lòng kiểm tra lại thông tin.',
      safeNote: 'Lưu tại CMS, chưa đổi website public.',
      leaveConfirm: 'Bạn có thay đổi chưa lưu. Rời màn này sẽ mất thay đổi. Tiếp tục?',
      noPermission: 'Tài khoản hiện tại chỉ được xem thông tin website.',
      logoReadonly: 'Logo website chỉ xem ở bước này. Chức năng thay logo sẽ mở sau khi có Media Upload.',
      statusReadonly: 'Trạng thái bản ghi CMS chỉ xem ở bước này.',
      fields: {
        site_title: 'Tên website',
        organization_name: 'Đơn vị quản lý',
        address: 'Địa chỉ',
        phone: 'Điện thoại',
        fax: 'Số fax',
        email: 'Thư điện tử',
        default_language: 'Ngôn ngữ mặc định',
        logo_url: 'Đường dẫn logo',
        site_status: 'Trạng thái bản ghi CMS',
      },
      placeholders: {
        site_title: 'Nhập tên website',
        organization_name: 'Nhập tên đơn vị quản lý',
        address: 'Nhập địa chỉ',
        phone: 'Nhập số điện thoại',
        fax: 'Nhập số fax',
        email: 'name@example.com',
      },
      errors: {
        siteTitleRequired: 'Tên website không được để trống.',
        organizationRequired: 'Đơn vị quản lý không được để trống.',
        emailInvalid: 'Thư điện tử không đúng định dạng.',
        languageInvalid: 'Ngôn ngữ mặc định không hợp lệ.',
      },
      warnings: {
        addressShort: 'Địa chỉ đang khá ngắn. Vui lòng kiểm tra lại trước khi công khai.',
        siteTitleLong: 'Tên website khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
        organizationLong: 'Tên đơn vị quản lý khá dài. Nên kiểm tra lại cách hiển thị trên giao diện public.',
      },
    },
  },
  maps: {
    roles: {
      admin: 'Quản trị viên',
      editor: 'Biên tập viên',
      unknown: 'Chưa rõ vai trò',
    },
    active: {
      true: 'Đang hoạt động',
      false: 'Không hoạt động',
    },
    status: {
      published: 'Đang công khai',
      archived: 'Đã lưu trữ',
      draft: 'Bản nháp',
      ok: 'Đang hoạt động',
      active: 'Đang bật',
      inactive: 'Đang tắt',
    },
    rooms: {
      indoor: 'Phòng trưng bày',
      outdoor: 'Không gian ngoài trời',
    },
    types: {
      artwork: 'Tác phẩm',
      video: 'Video',
      image: 'Hình ảnh',
      document: 'Tư liệu',
    },
    visible: {
      true: 'Đang hiển thị',
      false: 'Đang ẩn',
    },
    featured: {
      true: 'Có',
      false: 'Không',
    },
    warning: {
      empty: 'Không có',
      present: 'Có cảnh báo',
    },
    writeActions: {
      locked: 'Chưa bật chỉnh sửa',
      enabled: 'Đã bật chỉnh sửa',
      siteSettingsOnly: 'Chỉ bật Thông tin website',
      siteSettingsAndGate: 'Chỉ bật Thông tin website và Cổng vào',
    },
    viewMode: {
      on: 'Đang bật',
      off: 'Đang tắt',
    },
    languages: {
      vi: 'Tiếng Việt',
      en: 'Tiếng Anh',
    },
  },
  notices: {
    readOnly: 'Bạn đang xem dữ liệu nội dung. Chức năng chỉnh sửa sẽ được bật ở bước sau.',
    publicSafe: 'Đây là khóa chủ động để bảo vệ dữ liệu, không phải lỗi. Website public không bị ảnh hưởng trong bước này.',
    loading: 'Đang tải dữ liệu nội dung...',
    accessDeniedTitle: 'Tài khoản chưa được cấp quyền quản trị nội dung',
    accessDeniedFallback: 'Tài khoản chưa có hồ sơ quyền truy cập hoặc chưa được cấp quyền xem trang quản trị nội dung.',
    configWarningTitle: 'Chưa cấu hình kết nối dữ liệu cho trang quản trị nội dung',
    configWarningBody: 'Hãy cập nhật thông tin kết nối trong cấu hình trang quản trị. Không dùng khóa quyền cao trong trình duyệt.',
  },
});

export function getPageCopy(key) {
  return ADMIN_COPY.pages[key] || ADMIN_COPY.pages.dashboard;
}

export function getRoleLabel(role) {
  return ADMIN_COPY.maps.roles[role] || ADMIN_COPY.maps.roles.unknown;
}

export function getActiveLabel(isActive) {
  return isActive ? ADMIN_COPY.maps.active.true : ADMIN_COPY.maps.active.false;
}

export function getStatusLabel(status) {
  const key = String(status || '').toLowerCase();
  return ADMIN_COPY.maps.status[key] || status || '—';
}

export function getRoomLabel(roomKey) {
  return ADMIN_COPY.maps.rooms[roomKey] || roomKey || '—';
}

export function getContentTypeLabel(type) {
  return ADMIN_COPY.maps.types[type] || type || '—';
}

export function getVisibleLabel(value) {
  return value ? ADMIN_COPY.maps.visible.true : ADMIN_COPY.maps.visible.false;
}

export function getFeaturedLabel(value) {
  return value ? ADMIN_COPY.maps.featured.true : ADMIN_COPY.maps.featured.false;
}

export function getWarningLabel(value) {
  return value ? ADMIN_COPY.maps.warning.present : ADMIN_COPY.maps.warning.empty;
}

export function getLanguageLabel(language) {
  const key = String(language || '').toLowerCase();
  return ADMIN_COPY.maps.languages[key] || language || '—';
}

export function getFriendlyNote(note) {
  const text = String(note || '').trim();
  if (!text) return '—';
  if (text === 'Published by V6.11.20 backend foundation script.') {
    return 'Tạo bằng công cụ khởi tạo dữ liệu.';
  }
  return text;
}
